### ISSUE TITLE
Unable to turn the flash on (torch) while on a session. 

### ISSUE THREAD

**Issue by eugenio35** [opentok/opentok-android-sdk-samples#282] opened 2020-05-18 18:32 UTC
Hello

I'm using `opentok-android-sdk:2.16.6` and I'm adding Camera2 usage via sessions options like:

```
val options = object : Session.SessionOptions() {
     override fun isCamera2Capable(): Boolean = true
}

Session.Builder(context, apiKey, sessionId).sessionOptions(options).build().connect(token)
```

But I'm not able to turn the flash on using a suggestion from [Here](https://github.com/opentok/opentok-android-sdk-samples/issues/110#issuecomment-296682761):

```
CameraManager cm = (CameraManager)getSystemService(CAMERA_SERVICE);
try {
  cm.setTorchMode(cm.getCameraIdList()[0], true);
} catch (Exception ex) {
  ex.printStackTrace();
}
```

However if I call onPause() on the Session object, and then turn the flash on. It works fine until I call onResume() and then the flash dies again. 

Is there anyway we can accomplish this in an easy way without using a CustomVideoCapturer for this functionality? 

Are there any plans in the near future to include this functionality inside the CaptureSwitch interface? 

Thanks

_Originally posted by @eugenio35 in https://github.com/opentok/opentok-android-sdk-samples/issues/110#issuecomment-629876826_

**Comment by robjperez** [comment] 2020-06-03 14:14
Hi @eugenio35 

I've just retested that piece of code and it works for me without putting the session onPause.

Are you getting any exception when It does not work?
Which device are you using?, maybe the index of the array returned by `getCameraIdList()` is not the good one?

Going to close the issue since it does not look like samples or sdk issue.

**Comment by Flash91FS** [comment] 2020-06-08 10:57
Hi i am testing this same feature of turning on Flash on my device while streaming a session but it always gives my this exception **android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4): setTorchMode:1889: Torch for camera "0" is not available due to an existing camera user**  for Back Camera,  
and **android.hardware.camera2.CameraAccessException: MAX_CAMERAS_IN_USE (5): setTorchMode:1895: Torch for camera "0" is not available due to insufficient resources** for front facing camera on my Samsung Galaxy A20



`
2020-06-08 15:50:13.973 5787-5787/com.s.mirror I/CameraManager: setTorchMode : cameraId = 0, enabled = true
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err: android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4): setTorchMode:1889: Torch for camera "0" is not available due to an existing camera user
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:815)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at android.hardware.camera2.CameraManager$CameraManagerGlobal.setTorchMode(CameraManager.java:1085)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at android.hardware.camera2.CameraManager.setTorchMode(CameraManager.java:672)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at com.s.mirror.stream.view.activities.StreamPublishActivity.exitStream(StreamPublishActivity.kt:386)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:397)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at android.view.View.performClick(View.java:7339)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at android.widget.TextView.performClick(TextView.java:14222)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at android.view.View.performClickInternal(View.java:7305)
2020-06-08 15:50:13.976 5787-5787/com.s.mirror W/System.err:     at android.view.View.access$3200(View.java:846)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.view.View$PerformClick.run(View.java:27787)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7091)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err: Caused by: android.os.ServiceSpecificException: setTorchMode:1889: Torch for camera "0" is not available due to an existing camera user (code 7)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.os.Parcel.createException(Parcel.java:1980)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.os.Parcel.readException(Parcel.java:1934)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.os.Parcel.readException(Parcel.java:1884)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.hardware.ICameraService$Stub$Proxy.setTorchMode(ICameraService.java:559)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err:     at android.hardware.camera2.CameraManager$CameraManagerGlobal.setTorchMode(CameraManager.java:1083)
2020-06-08 15:50:13.977 5787-5787/com.s.mirror W/System.err: 	... 16 more`

**Comment by eugenio35** [comment] 2020-06-08 15:11
Hey @robjperez thanks for replying. And yes, the error I get is really similar to the one @Flash91FS is reporting. 

*android.hardware.camera2.CameraAccessException: The camera device is in use already*

Any help with this feature will be really appreciate it.

**Comment by robjperez** [comment] 2020-06-09 08:40
Hi, I could reproduce the issue.

Unfortunately there is no other solution rather than using a custom capturer.

You can use this as a base: https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Capturer-Camera2

And in the capturer add this code:

```java
    public void setTorch(boolean enabled) {
        try {
            captureSession.stopRepeating();
            captureRequestBuilder.set(CaptureRequest.FLASH_MODE, enabled ? CaptureRequest.FLASH_MODE_TORCH : null);
            captureSession.setRepeatingRequest(captureRequestBuilder.build(), captureNotification, null);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
```

I will add this a future improvement of the sdk, but at this point, this is the only solution.

**Closed by robjperez** 2020-06-09 08:40 UTC

**Comment by Flash91FS** [comment] 2020-06-09 11:56
Hi @robjperez, 

Unfortunately this method didn't work as well. I used the **CustomVideoCapturerCamera2** and added it to the publisher as shown below:

`mCapturer = CustomVideoCapturerCamera2(
            this,
            Publisher.CameraCaptureResolution.HIGH,
            Publisher.CameraCaptureFrameRate.FPS_30
        )
        mPublisher = Publisher.Builder(this)
            .name("publisher")
            .capturer(
                mCapturer
            )
            .build()
        mPublisher!!.setPublisherListener(this)
        mPublisher!!.setPublishAudio(OpenTokConfiguration.isAudioEnable)

        mPublisher!!.setStyle(
            BaseVideoRenderer.STYLE_VIDEO_SCALE,
            BaseVideoRenderer.STYLE_VIDEO_FILL
        )`

and even added the method you stated in the CustomVideoCapturerCamera2 class and the tried calling it later to see if it work using either of these to methods below

`fun turnOnFlash() {
        try {
            mCapturer!!.setTorch(true)
        } catch (ex: Exception) {
            ex.printStackTrace()
        }
    }`

and 

`fun turnOnTorch() {
        try {
           val cap =  mPublisher!!.capturer as CustomVideoCapturerCamera2
            cap.setTorch(true)
        } catch (ex: Exception) {
            ex.printStackTrace()
        }
    }`

but none of this worked at all, and one more issue i faced after using this CustomVideoCapturerCamera2 for my Publisher is that, upon quitting the session and then trying to connect a new session it would show me a Blank screen, and upon calling the setTorch method it would give me this Exception below


java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.stopRepeating()' on a null object reference
2020-06-09 16:54:04.720 32649-32649/com.s.mirror W/System.err:     at com.example.tokbox.CustomVideoDriverLib.CustomVideoCapturerCamera2.setTorch(CustomVideoCapturerCamera2.java:697)


Meaning that **captureSession** wasn't initialized upon trying to have a new session (after destroying the previous one like in the example)

**Comment by eugenio35** [comment] 2020-06-09 15:46
Hey @robjperez thanks for adding this as a feature request. I think this way is more elegant than adding the CustomVideoCapturer class.

**Comment by Flash91FS** [comment] 2020-06-10 03:52
@eugenio35 did it work for you?

**Comment by predictcare** [comment] 2023-03-01 11:42
@robjperez we are struggling try to manage to implement a button to start and stop flashlight while in video call.

Could you help us managing this ? We don't use any CustomVideoCapturer.

Was this enhancement passed in production ?

Thanks !
