### ISSUE TITLE
[Crash] A/libc: Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by sebandres** [opentok/opentok-android-sdk-samples#225] opened 2019-05-30 01:19 UTC
Present in version 2.16.0. Tested with version 2.15.3 and works fine.

Deploying to device with Android 4.2.2.
minSdkVersion 17
targetSdkVersion 17

Steps to reproduce:
Download build and deploy:
https://github.com/opentok/opentok-android-sdk-samples/tree/master/Basic-Video-Chat

Crash happens as soon as the preview window is open.

`A/libc: Fatal signal 11 (SIGSEGV) at 0x0000003c (code=1), thread 4077 (Thread 0x0x539f)`

**Comment by anmarbro** [comment] 2019-07-08 08:30
Same happening on Android 5.1.1 API 22.
Working fine on version 2.15.3 but crashing on 2.16.0

Are there any news about this issue?

**Comment by janoonaj** [comment] 2019-07-11 06:58
Also happens here. **NOT FIXED IN 2.16.1**

Any ideas? We can't update our app because of that.

**Comment by raipradeep** [comment] 2019-07-26 09:15
Getting this issue when disconnet, how to solve this ??
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 13435 (Thread-20), pid 13187

**Comment by GiacomoDB** [comment] 2019-08-20 14:13
Same issue with disconnecting a session

**Comment by maxsdev** [comment] 2019-08-21 05:23
Same issue with disconnecting a session.
And when subscriber try to subscribe on streans.

**Comment by mark-veenstra** [comment] 2019-08-26 08:09
All related to #236

**Comment by shahalRahman** [comment] 2020-01-02 06:06
Facing the same issue in 2.16.3 as well.
`signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x70`

**Comment by msach22** [comment] 2020-01-02 06:59
@shahalRahman Thanks for sharing. Are you simply seeing this when building the basic video chat app?

**Comment by shahalRahman** [comment] 2020-01-02 07:37
No,We're using it in our application. We have already reported this issue for 2.15.3 version. Crash happened on disconnecting the call.

**Comment by msach22** [comment] 2020-01-02 18:45
@shahalRahman 2.15 has not been a supported version for quite some time now.  Could you please try with 2.16.3?

**Comment by shahalRahman** [comment] 2020-01-03 11:15
As I've said, this same issue which we faced in 2.15.3 we're facing in 2.16.3.

**Comment by msach22** [comment] 2020-01-03 22:28
It would be helpful to have reproduction steps - please share if you have them. We are unable to reproduce this crash with 2.16.3 using the basic video chat samples.

**Comment by ukevgen** [comment] 2020-05-06 12:07
2.17 the same

**Comment by robjperez** [comment] 2020-05-06 16:36
@ukevgen can you provide more details please?

Which Device/Android version are you using?
Can you share the dump of the crash?

**Comment by robjperez** [comment] 2020-05-28 14:16
@ukevgen I'm going to close the issue due to inactivity. Please reopen it if it still crashing

**Closed by robjperez** 2020-05-28 14:16 UTC
