### ISSUE TITLE
[OPENTOK-42796] PublisherTimeout - Timed out while attempting to publish

### ISSUE THREAD

**Issue by emjoseph** [opentok/opentok-android-sdk-samples#324] opened 2020-12-12 00:59 UTC
I'm running OpenTok for Android (2.18.1) on a Pixel 4a running Android 11. The sample Basic-Video-Chat app works as long as the targetSdkVersion is 28, but once I change that 29 or 30, the video preview is black and video is no longer broadcasted. Here's the full LogCat:
```
2020-12-11 17:26:58.534 11838-11838/? I/asic_video_cha: Late-enabling -Xcheck:jni
2020-12-11 17:26:58.551 11838-11838/? I/asic_video_cha: Unquickening 12 vdex files!
2020-12-11 17:26:58.650 11838-11838/com.tokbox.android.tutorials.basic_video_chat W/ActivityThread: Application com.tokbox.android.tutorials.basic_video_chat is waiting for the debugger on port 8100...
2020-12-11 17:26:58.653 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: Sending WAIT chunk
2020-12-11 17:26:59.653 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: Debugger has connected
2020-12-11 17:26:59.654 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: waiting for debugger to settle...
2020-12-11 17:26:59.854 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: waiting for debugger to settle...
2020-12-11 17:27:00.054 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: waiting for debugger to settle...
2020-12-11 17:27:00.255 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: waiting for debugger to settle...
2020-12-11 17:27:00.455 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: waiting for debugger to settle...
2020-12-11 17:27:00.656 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: waiting for debugger to settle...
2020-12-11 17:27:00.857 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: waiting for debugger to settle...
2020-12-11 17:27:01.058 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: waiting for debugger to settle...
2020-12-11 17:27:01.258 11838-11838/com.tokbox.android.tutorials.basic_video_chat I/System.out: debugger has settled (1300)
2020-12-11 17:27:01.359 11838-11838/com.tokbox.android.tutorials.basic_video_chat D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-12-11 17:27:01.364 11838-11838/com.tokbox.android.tutorials.basic_video_chat D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-12-11 17:27:01.462 11838-11838/com.tokbox.android.tutorials.basic_video_chat D/MainActivity: onCreate
2020-12-11 17:27:01.615 11838-11838/com.tokbox.android.tutorials.basic_video_chat W/asic_video_cha: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2020-12-11 17:27:01.616 11838-11838/com.tokbox.android.tutorials.basic_video_chat W/asic_video_cha: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2020-12-11 17:27:01.706 11838-11838/com.tokbox.android.tutorials.basic_video_chat W/asic_video_chat: type=1400 audit(0.0:437): avc: denied { read } for name="sdcard" dev="tmpfs" ino=2046 scontext=u:r:untrusted_app:s0:c230,c256,c512,c768 tcontext=u:object_r:mnt_sdcard_file:s0 tclass=lnk_file permissive=0 app=com.tokbox.android.tutorials.basic_video_chat
2020-12-11 17:27:01.710 11838-11838/com.tokbox.android.tutorials.basic_video_chat V/[com.opentok.android]: *********************** OpenTok Android SDK ****************************
    **** Version/Revision: android-2.18.1/4d79119113369a111860b70647702b98d098f6df
    **** Library built on: Oct  2 2020
    **** Copyright 2020 TokBox, Inc.
    **** Licensed under the Apache License, Version 2.0
    ****
2020-12-11 17:27:01.783 11838-11838/com.tokbox.android.tutorials.basic_video_chat D/MainActivity: onResume
2020-12-11 17:27:01.908 11838-12116/com.tokbox.android.tutorials.basic_video_chat I/AdrenoGLES-0: QUALCOMM build                   : 0905e9f, Ia11ce2d146
    Build Date                       : 09/02/20
    OpenGL ES Shader Compiler Version: EV031.31.04.00
    Local Branch                     : gfx-adreno.lnx.2.0
    Remote Branch                    :
    Remote Branch                    :
    Reconstruct Branch               :
2020-12-11 17:27:01.908 11838-12116/com.tokbox.android.tutorials.basic_video_chat I/AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
2020-12-11 17:27:01.908 11838-12116/com.tokbox.android.tutorials.basic_video_chat I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2020-12-11 17:27:01.917 11838-12116/com.tokbox.android.tutorials.basic_video_chat I/AdrenoGLES-0: PFP: 0x016ee189, ME: 0x00000000
2020-12-11 17:27:01.921 11838-12116/com.tokbox.android.tutorials.basic_video_chat W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2020-12-11 17:27:01.921 11838-12116/com.tokbox.android.tutorials.basic_video_chat W/AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2020-12-11 17:27:01.943 11838-12116/com.tokbox.android.tutorials.basic_video_chat I/Gralloc4: mapper 4.x is not supported
2020-12-11 17:27:03.132 11838-11838/com.tokbox.android.tutorials.basic_video_chat W/VideoCapabilities: Unsupported mime image/vnd.android.heic
2020-12-11 17:27:03.249 11838-11838/com.tokbox.android.tutorials.basic_video_chat D/MainActivity: onConnected: Connected to session: 2_MX40Njk2MDg4NH5-MTYwNzczMjk4MTc4OX5kNDFYY01hT25pZEJqa0ZPWHMxdk5mZVJ-fg
2020-12-11 17:27:03.448 11838-12466/com.tokbox.android.tutorials.basic_video_chat W/AudioManager: Use of stream types is deprecated for operations other than volume control
2020-12-11 17:27:03.448 11838-12466/com.tokbox.android.tutorials.basic_video_chat W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2020-12-11 17:27:03.484 11838-12466/com.tokbox.android.tutorials.basic_video_chat W/AudioTrack: Use of stream types is deprecated for operations other than volume control
2020-12-11 17:27:03.484 11838-12466/com.tokbox.android.tutorials.basic_video_chat W/AudioTrack: See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2020-12-11 17:27:03.492 11838-12466/com.tokbox.android.tutorials.basic_video_chat D/CompatibilityChangeReporter: Compat change id reported: 147600208; UID 10230; state: ENABLED
2020-12-11 17:27:03.536 11838-11857/com.tokbox.android.tutorials.basic_video_chat W/Gralloc4: allocator 3.x is not supported
2020-12-11 17:27:03.593 11838-12464/com.tokbox.android.tutorials.basic_video_chat D/[DefaultVideoRenderer(native)]: VideoRenderOpenGles20: id 0
2020-12-11 17:27:03.594 11838-12464/com.tokbox.android.tutorials.basic_video_chat D/[DefaultVideoRenderer(native)]: Setup: width 236, height 318
2020-12-11 17:27:03.594 11838-12464/com.tokbox.android.tutorials.basic_video_chat D/[DefaultVideoRenderer(native)]: Setup: number of textures 16, size 16384
2020-12-11 17:27:18.885 11838-11838/com.tokbox.android.tutorials.basic_video_chat E/MainActivity: onError: PublisherErrorDomain : PublisherTimeout - Timed out while attempting to publish.
2020-12-11 17:27:18.889 11838-11838/com.tokbox.android.tutorials.basic_video_chat D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10230; state: ENABLED
2020-12-11 17:27:18.920 11838-11838/com.tokbox.android.tutorials.basic_video_chat D/MainActivity: onPause
2020-12-11 17:27:19.196 11838-12466/com.tokbox.android.tutorials.basic_video_chat D/AudioTrack: stop(43): called with 746976 frames delivered
```

The above configuration (same OpenTok and Android configuration) does weirdly work on my Pixel 2 and video successfully broadcasts.

**Comment by adrienrx** [comment] 2020-12-15 09:27
Yep same here https://support.tokbox.com/hc/requests/1529476

**Comment by igorwojda** [comment] 2021-01-14 14:04
This seems to happen on other devices as well. I have reproduced this issue with `Custom-Capturer-Camera2` sample (this repo).

**Test scenario:**
- open `Custom-Capturer-Camera2` project
- set all keys and tokens in the `OpenTokConfig.java`
- Go to [Opentok Playgorund](https://tokbox.com/developer/tools/playground/) and publish one stream to the same session (I am not sure if this step actually matters)
- Run the app multiple times from Android Studio

**Test results**
I did 30 runs on each of the following devices: 
- OnePlus 7T, Android 10 (5 times black screen / 25 times OK)
- Google Pixel 4, Android 11 (3 times black screen / 27 times OK)

Sometimes you can run the app 15 times and it will be fine, but the next run will fail to publish.


Logcat contains `onError: Error (Timed out while attempting to publish.) in publisher` line:

OpenPlus 7T logcat:
```
2021-01-14 12:28:18.243 15818-15818/? I/rials.archivin: Late-enabling -Xcheck:jni
2021-01-14 12:28:18.253 15818-15818/com.tokbox.android.tutorials.archiving E/rials.archivin: Unknown bits set in runtime_flags: 0x8000
2021-01-14 12:28:18.291 15818-15818/com.tokbox.android.tutorials.archiving I/Perf: Connecting to perf service.
2021-01-14 12:28:18.294 15818-15818/com.tokbox.android.tutorials.archiving I/rials.archivin: [GL_OOM] ClampGrowthLimit 268435456
2021-01-14 12:28:18.298 15818-15854/com.tokbox.android.tutorials.archiving E/Perf: Fail to get file list com.tokbox.android.tutorials.archiving
2021-01-14 12:28:18.298 15818-15854/com.tokbox.android.tutorials.archiving E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-01-14 12:28:18.298 15818-15854/com.tokbox.android.tutorials.archiving E/Perf: Fail to get file list com.tokbox.android.tutorials.archiving
2021-01-14 12:28:18.298 15818-15854/com.tokbox.android.tutorials.archiving E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-01-14 12:28:18.298 15818-15854/com.tokbox.android.tutorials.archiving E/Perf: Fail to get file list oat
2021-01-14 12:28:18.298 15818-15854/com.tokbox.android.tutorials.archiving E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-01-14 12:28:18.338 15818-15818/com.tokbox.android.tutorials.archiving W/rials.archivin: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-01-14 12:28:18.339 15818-15818/com.tokbox.android.tutorials.archiving W/rials.archivin: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-01-14 12:28:18.366 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onResume
2021-01-14 12:28:18.386 15818-15878/com.tokbox.android.tutorials.archiving D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@2bee6ce[MainActivity]
2021-01-14 12:28:18.387 15818-15856/com.tokbox.android.tutorials.archiving I/AdrenoGLES: QUALCOMM build                   : bc92c36, I9e73322269
    Build Date                       : 08/28/19
    OpenGL ES Shader Compiler Version: EV031.27.02.00
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.8.1.R1.09.00.00.529.074
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2021-01-14 12:28:18.388 15818-15856/com.tokbox.android.tutorials.archiving I/AdrenoGLES: Build Config                     : S P 8.0.8 AArch64
2021-01-14 12:28:18.390 15818-15856/com.tokbox.android.tutorials.archiving I/AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
2021-01-14 12:28:18.401 15818-15856/com.tokbox.android.tutorials.archiving W/Gralloc3: mapper 3.x is not supported
2021-01-14 12:28:20.563 15818-15818/com.tokbox.android.tutorials.archiving W/VideoCapabilities: Unsupported mime image/vnd.android.heic
2021-01-14 12:28:20.572 15818-15818/com.tokbox.android.tutorials.archiving W/VideoCapabilities: Unsupported mime video/divx
2021-01-14 12:28:20.572 15818-15818/com.tokbox.android.tutorials.archiving W/VideoCapabilities: Unsupported mime video/divx4
2021-01-14 12:28:20.575 15818-15818/com.tokbox.android.tutorials.archiving W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2021-01-14 12:28:20.575 15818-15818/com.tokbox.android.tutorials.archiving W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2021-01-14 12:28:20.576 15818-15818/com.tokbox.android.tutorials.archiving W/VideoCapabilities: Unsupported mime video/x-ms-wmv
2021-01-14 12:28:20.605 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onConnected: Connected to session 2_MX40Njc4Nzk4NH5-MTYxMDQ0MzgwOTU3Nn4xRmx2Q2RjWlpGYjVrRkhmRUFlKzZ4M1d-fg
2021-01-14 12:28:20.606 15818-15818/com.tokbox.android.tutorials.archiving I/CameraManagerGlobal: Connecting to camera service
2021-01-14 12:28:20.608 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving I/chatty: uid=10254(com.tokbox.android.tutorials.archiving) identical 1 line
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 2
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 3
2021-01-14 12:28:20.600 15818-15818/com.tokbox.android.tutorials.archiving W/rials.archiving: type=1400 audit(0.0:24401): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=26207 scontext=u:r:untrusted_app_27:s0:c254,c256,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2021-01-14 12:28:20.600 15818-15818/com.tokbox.android.tutorials.archiving I/chatty: uid=10254(com.tokbox.android.tutorials.archiving) identical 1 line
2021-01-14 12:28:20.600 15818-15818/com.tokbox.android.tutorials.archiving W/rials.archiving: type=1400 audit(0.0:24403): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=26207 scontext=u:r:untrusted_app_27:s0:c254,c256,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 4
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 5
2021-01-14 12:28:20.609 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.609 15818-15878/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.600 15818-15818/com.tokbox.android.tutorials.archiving W/rials.archiving: type=1400 audit(0.0:24404): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=26207 scontext=u:r:untrusted_app_27:s0:c254,c256,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2021-01-14 12:28:20.600 15818-15818/com.tokbox.android.tutorials.archiving I/chatty: uid=10254(com.tokbox.android.tutorials.archiving) identical 2 lines
2021-01-14 12:28:20.600 15818-15818/com.tokbox.android.tutorials.archiving W/rials.archiving: type=1400 audit(0.0:24407): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=26207 scontext=u:r:untrusted_app_27:s0:c254,c256,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2021-01-14 12:28:20.600 15818-15818/com.tokbox.android.tutorials.archiving W/Binder:15818_4: type=1400 audit(0.0:24408): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=26207 scontext=u:r:untrusted_app_27:s0:c254,c256,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2021-01-14 12:28:20.612 15818-15818/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: selectCamera() Direction the camera faces relative to device screen: 0
2021-01-14 12:28:20.612 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.610 15818-15818/com.tokbox.android.tutorials.archiving W/rials.archiving: type=1400 audit(0.0:24409): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=26207 scontext=u:r:untrusted_app_27:s0:c254,c256,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2021-01-14 12:28:20.627 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onStreamReceived: New stream 19db2119-9b1a-4e22-ac46-e04798585a63 in session 2_MX40Njc4Nzk4NH5-MTYxMDQ0MzgwOTU3Nn4xRmx2Q2RjWlpGYjVrRkhmRUFlKzZ4M1d-fg
2021-01-14 12:28:20.630 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onStreamReceived: New stream 26129e99-a6d3-4e28-8dd4-89abb7675095 in session 2_MX40Njc4Nzk4NH5-MTYxMDQ0MzgwOTU3Nn4xRmx2Q2RjWlpGYjVrRkhmRUFlKzZ4M1d-fg
2021-01-14 12:28:20.630 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onStreamReceived: New stream b95a986b-0168-49b0-8640-02b2dbf0e28b in session 2_MX40Njc4Nzk4NH5-MTYxMDQ0MzgwOTU3Nn4xRmx2Q2RjWlpGYjVrRkhmRUFlKzZ4M1d-fg
2021-01-14 12:28:20.630 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onStreamReceived: New stream 64a4706f-88da-45b9-8b50-43b23cc63ec4 in session 2_MX40Njc4Nzk4NH5-MTYxMDQ0MzgwOTU3Nn4xRmx2Q2RjWlpGYjVrRkhmRUFlKzZ4M1d-fg
2021-01-14 12:28:20.630 15818-15818/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: init enter
2021-01-14 12:28:20.631 15818-15818/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: initCamera()
2021-01-14 12:28:20.631 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.631 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.649 15818-15818/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "persist.vendor.camera.privapp.list"
2021-01-14 12:28:20.658 15818-15878/com.tokbox.android.tutorials.archiving E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-14 12:28:20.670 15818-15818/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: init exit
2021-01-14 12:28:20.670 15818-15818/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: startCapture enter (cameraState: SETUP)
2021-01-14 12:28:20.670 15818-15818/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: camera not yet ready, queuing the start until camera is opened.
2021-01-14 12:28:20.670 15818-15904/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: CameraDevice onOpened
2021-01-14 12:28:20.670 15818-15818/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: startCapture exit
2021-01-14 12:28:20.708 15818-15897/com.tokbox.android.tutorials.archiving D/[DefaultVideoRenderer(native)]: VideoRenderOpenGles20: id 0
2021-01-14 12:28:20.708 15818-15897/com.tokbox.android.tutorials.archiving D/[DefaultVideoRenderer(native)]: Setup: width 352, height 483
2021-01-14 12:28:20.708 15818-15897/com.tokbox.android.tutorials.archiving D/[DefaultVideoRenderer(native)]: Setup: number of textures 16, size 16384
2021-01-14 12:28:20.744 15818-15899/com.tokbox.android.tutorials.archiving W/AudioManager: Use of stream types is deprecated for operations other than volume control
2021-01-14 12:28:20.744 15818-15899/com.tokbox.android.tutorials.archiving W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2021-01-14 12:28:20.749 15818-15899/com.tokbox.android.tutorials.archiving I/AudioManager: In isBluetoothScoAvailableOffCall(), calling appilication: com.tokbox.android.tutorials.archiving, return value: true
2021-01-14 12:28:20.752 15818-15899/com.tokbox.android.tutorials.archiving I/AudioManager: In setBluetoothScoOn(), on: true, calling application: com.tokbox.android.tutorials.archiving
2021-01-14 12:28:20.752 15818-15899/com.tokbox.android.tutorials.archiving I/AudioManager: In startbluetoothSco(), calling application: com.tokbox.android.tutorials.archiving
2021-01-14 12:28:20.752 15818-15818/com.tokbox.android.tutorials.archiving I/AudioManager: In setSpeakerphoneOn(), on: true, calling application: com.tokbox.android.tutorials.archiving
2021-01-14 12:28:20.754 15818-15899/com.tokbox.android.tutorials.archiving I/ELEVOC_NS_FRONT: cycle task init 0x771e40d740
2021-01-14 12:28:20.754 15818-15899/com.tokbox.android.tutorials.archiving D/AudioTrack: set(): streamType -1, sampleRate 48000, format 0x1, channelMask 0x1, frameCount 3844, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
2021-01-14 12:28:20.769 15818-15899/com.tokbox.android.tutorials.archiving W/AudioTrack: Use of stream types is deprecated for operations other than volume control
2021-01-14 12:28:20.769 15818-15899/com.tokbox.android.tutorials.archiving W/AudioTrack: See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2021-01-14 12:28:20.773 15818-15899/com.tokbox.android.tutorials.archiving I/AudioManager: In setSpeakerphoneOn(), on: true, calling application: com.tokbox.android.tutorials.archiving
2021-01-14 12:28:20.774 15818-15899/com.tokbox.android.tutorials.archiving I/OnePlusAudioTrackInjector: play() packageName: com.tokbox.android.tutorials.archiving
2021-01-14 12:28:20.774 15818-15899/com.tokbox.android.tutorials.archiving I/OnePlusAudioTrackInjector: bufferSizeInBytes:7688, sampleRate:48000
2021-01-14 12:28:20.775 15818-15899/com.tokbox.android.tutorials.archiving D/AudioTrack: ClientUid 10254 AudioTrack::start 
2021-01-14 12:28:20.776 15818-15899/com.tokbox.android.tutorials.archiving I/ELEVOC_NS_FRONT: cycle start task... 0x771e40d740
2021-01-14 12:28:20.776 15818-15899/com.tokbox.android.tutorials.archiving D/ELEVOC_NS_FRONT: cycle start task succ! 0x771e40d740
2021-01-14 12:28:20.787 15818-15899/com.tokbox.android.tutorials.archiving I/AudioManager: In setMode(), mode: 3, calling application: com.tokbox.android.tutorials.archiving
2021-01-14 12:28:21.362 15818-15818/com.tokbox.android.tutorials.archiving D/OpScreenModeManager: setRefreshRate token android.os.BinderProxy@f34aeca rate 1 mCurrentRate 0
2021-01-14 12:28:21.363 15818-15818/com.tokbox.android.tutorials.archiving D/OpScreenModeManager: updateScenario fullScreen 1
2021-01-14 12:28:21.364 15818-15903/com.tokbox.android.tutorials.archiving D/[DefaultVideoRenderer(native)]: VideoRenderOpenGles20: id 0
2021-01-14 12:28:21.364 15818-15903/com.tokbox.android.tutorials.archiving D/[DefaultVideoRenderer(native)]: Setup: width 996, height 2047
2021-01-14 12:28:21.364 15818-15903/com.tokbox.android.tutorials.archiving D/[DefaultVideoRenderer(native)]: Setup: number of textures 16, size 16384
2021-01-14 12:28:23.764 15818-15818/com.tokbox.android.tutorials.archiving I/AudioManager: In setSpeakerphoneOn(), on: true, calling application: com.tokbox.android.tutorials.archiving
2021-01-14 12:28:36.358 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onError: Error (Timed out while attempting to publish.) in publisher
2021-01-14 12:28:36.462 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onPause
2021-01-14 12:28:36.495 15818-15818/com.tokbox.android.tutorials.archiving D/CustomVideoCapturerCamera2: onPause
2021-01-14 12:28:36.501 15818-15818/com.tokbox.android.tutorials.archiving D/OpScreenModeManager: setRefreshRate token android.os.BinderProxy@f34aeca rate 0 mCurrentRate 1
2021-01-14 12:28:36.501 15818-15818/com.tokbox.android.tutorials.archiving D/OpScreenModeManager: updateScenario fullScreen 0
2021-01-14 12:28:36.571 15818-15899/com.tokbox.android.tutorials.archiving I/OnePlusAudioTrackInjector: stop() packageName: com.tokbox.android.tutorials.archiving, sampleRate: 48000
2021-01-14 12:28:36.572 15818-15899/com.tokbox.android.tutorials.archiving D/AudioTrack: ClientUid 10254 AudioTrack::stop 
2021-01-14 12:28:36.572 15818-15899/com.tokbox.android.tutorials.archiving I/ELEVOC_NS_FRONT: cycle stop task... 0x771e40d740
2021-01-14 12:28:36.572 15818-15899/com.tokbox.android.tutorials.archiving D/AudioTrack: stop(1177): called with 760704 frames delivered
2021-01-14 12:28:36.572 15818-15899/com.tokbox.android.tutorials.archiving I/AudioManager: In setMode(), mode: 0, calling application: com.tokbox.android.tutorials.archiving
2021-01-14 12:28:36.723 15818-15818/com.tokbox.android.tutorials.archiving W/Choreographer: Already have a pending vsync event.  There should only be one at a time.
2021-01-14 12:28:36.732 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onError: Error ((null description)) in session 2_MX40Njc4Nzk4NH5-MTYxMDQ0MzgwOTU3Nn4xRmx2Q2RjWlpGYjVrRkhmRUFlKzZ4M1d-fg
2021-01-14 12:28:36.754 15818-15818/com.tokbox.android.tutorials.archiving D/MainActivity: onDisconnected: disconnected from session 2_MX40Njc4Nzk4NH5-MTYxMDQ0MzgwOTU3Nn4xRmx2Q2RjWlpGYjVrRkhmRUFlKzZ4M1d-fg
```

**Comment by AndreasKarlzzon** [comment] 2021-01-19 07:57
+1

**Comment by patrik90909** [comment] 2021-01-27 17:46
+1

**Comment by igorwojda** [comment] 2021-02-16 10:02
Should be fixed in the upcoming 2.19 release.

**Comment by igorwojda** [comment] 2021-02-18 11:18
It looks like 2.19 does not address this specific issue. We are looking into this.

**Comment by igorwojda** [comment] 2021-03-01 11:20
We are unable to reproduce this anymore, so I will close this issue.

**Closed by igorwojda** 2021-03-01 11:20 UTC
Labels: bug
