### ISSUE TITLE
The camera device has been disconnected

### ISSUE THREAD

**Issue by pomegra** [opentok/opentok-android-sdk-samples#469] opened 2023-06-25 10:24 UTC
E/CameraCaptureSession(14214): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(14214): android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): checkPidStatus:1933: The camera device has been disconnected
E/CameraCaptureSession(14214): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1179)
E/CameraCaptureSession(14214): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession(14214): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1287)
E/CameraCaptureSession(14214): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(14214): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:790)
E/CameraCaptureSession(14214): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:259)
E/CameraCaptureSession(14214): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(14214): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(14214): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CameraCaptureSession(14214): 	at android.os.Looper.loop(Looper.java:288)
E/CameraCaptureSession(14214): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/CameraCaptureSession(14214): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(14214): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/CameraCaptureSession(14214): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/CameraCaptureSession(14214): Caused by: android.os.ServiceSpecificException: checkPidStatus:1933: The camera device has been disconnected (code 4)
E/CameraCaptureSession(14214): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2439)
E/CameraCaptureSession(14214): 	at android.os.Parcel.createException(Parcel.java:2409)
E/CameraCaptureSession(14214): 	at android.os.Parcel.readException(Parcel.java:2392)
E/CameraCaptureSession(14214): 	at android.os.Parcel.readException(Parcel.java:2334)
E/CameraCaptureSession(14214): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:749)
E/CameraCaptureSession(14214): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession(14214): 	... 12 more

**Comment by v-kpheng** [comment] 2023-07-05 21:57
@pomegra, I'm going to close this since it's missing some key details, like devices impacted, steps to reproduce, etc.  Can you please refile and answer the questions in the template?

**Closed by v-kpheng** 2023-07-05 21:57 UTC
