### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference

### ISSUE THREAD

**Issue by derekpitts28** [opentok/opentok-android-sdk-samples#476] opened 2023-09-12 23:41 UTC
**Describe the bug**
This is happening on production for us also.
Device: Pixel 6 Android 13
Vonage SDK: 2.26

We see this occur when closing a previous session and creating a new close together. There seems to be no 'good' or recommended way to close a session other than nulling its reference and hoping that the garbage collector collects. That being said we are trying to use the life cycle methods to gracefully close the vonage session. 

The main issue seems to be that vonage is attempting to remove something that does not exist or is already stopped.

The fact that I have to jump though so many hoops just to dispose and ensure vonage is not controlling the camera anymore is a bit crazy to me.

```
FATAL EXCEPTION: main
Process: com.transcarent.app, PID: 550
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
	at com.opentok.android.Camera2VideoCapturer.stopDisplayOrientationCache(Unknown Source:4)
	at com.opentok.android.Camera2VideoCapturer.destroy(Unknown Source:11)
	at com.opentok.android.PublisherKit.a(Unknown Source:4)
	at com.opentok.android.PublisherKit.z(Unknown Source:0)
	at com.opentok.android.m0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

It should be noted we have also tried to go directly to the capture of the publisher and stop that however stopping that results in a separate error.

Please give us a guaranteed way to COMPLETELY dispose of a session/publisher this is so frustrating.

I believe this error seems to be due to the SDK expecting a callback but because i removed it it is getting null. Is your SDK nullsafe on the java side when running callbacks that can be nulled?

**To Reproduce**
If you run this code to close the previous sessions references x3-4 times you will run into the error i got.
```
// Fully connect to a session
// Leave. session

patientPublisher?.setPublisherListener(null)
patientPublisher?.setMuteListener(null)
patientPublisher?.setCameraListener(null)
patientPublisher?.setVideoListener(null)

session?.onPause()
patientPublisher?.onStop()
```

**Expected behavior**
The session is closed without throwing errors.

**Device (please compete the following information):**
Device: Pixel 6 Android 13
Vonage SDK: 2.26

**Additional context**

**Comment by goncalocostamendes** [comment] 2023-09-19 19:15
@derekpitts28 

In a soon to be released v2.26.1 version (between this and the following week), we currectly terminate the camera capturer for all scenarios.

When combining the 2.26.1 version together with the correct way to gracefully terminate a session:

```
mPublisher.onStop();
mSession.unpublish(mPublisher);
mSession.disconnect();
```

I attached a video recording to the ticket showing reproducing the scenario with the new fixes:
https://github.com/opentok/opentok-android-sdk-samples/assets/106695857/386057f6-36af-4fee-adbd-85b1282d8d78

I will close the ticket. If for some reason you find these changes do not solve your problem, please re-open it.

**Comment by derekpitts28** [comment] 2023-09-20 14:21
Thanks so much @goncalocostamendes !!

**Comment by goncalocostamendes** [comment] 2023-09-20 15:16
@v-kpheng can you please give a feedback to @derekpitts28?

**Comment by v-kpheng** [comment] 2023-09-20 16:51
@derekpitts28, 2.26.1 should be out by mid-October.

**Comment by derekpitts28** [comment] 2023-11-07 20:10
@goncalocostamendes After we updated to the new 2.26.1 and using the closing code you mentioned above, our testers still found this issue on android Xiaomi API 33. I am wondering if this is a race condition because on average i am not reproducing this on my Pixel 6 but we are seeing it consistently on other devices. 

Could we surround these calls with a try catch or add in null safe calls so we don't see stale calls call this? This is completely bricking the app when it happens.

Here is the error again:
```
digest=============com.transcarent.appjava.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
at com.opentok.android.CameraVideoCapturer.stopDisplayOrientationCache(SourceFile:)
at com.opentok.android.CameraVideoCapturer.destroy(SourceFile:XX)
at com.opentok.android.PublisherKit.a(SourceFile:)
at com.opentok.android.PublisherKit.z(SourceFile:)
at com.opentok.android.q.run(R$$SyntheticClass:)
at android.os.Handler.handleCallback(Handler.java:XX)
at android.os.Handler.dispatchMessage(Handler.java:XX)
at android.os.Looper.loopOnce(Looper.java:XX)
at android.os.Looper.loop(Looper.java:XX)
at android.app.ActivityThread.main(ActivityThread.java:XX)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:XX)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:XX)
```

**Comment by derekpitts28** [comment] 2023-11-07 20:38
I believe you said i can reopen this however i do not think i have the ability to do so, please let me know how you want me to proceed when you have a chance, thanks!

**Comment by goncalocostamendes** [comment] 2023-11-08 18:36
Reopening issue @derekpitts28

**Comment by derekpitts28** [comment] 2023-11-27 15:19
Any movement on this? @goncalocostamendes @v-kpheng

**Comment by derekpitts28** [comment] 2023-12-12 19:54
@goncalocostamendes @v-kpheng Any way I can get this looked at, we have users crashing because of this, thanks!

**Comment by goncalocostamendes** [comment] 2023-12-14 17:32
@derekpitts28 I can now have access to a mobile device with the same model. This bug will be worked on next sprint. I will provide you an update once I have one.

Please provide me the entire content of the function you call to end the session.

**Comment by derekpitts28** [comment] 2023-12-15 18:37
Here is the dispose call:

```
    private fun dispose() {
        try {
            patientPublisher?.onStop()
        } catch (e: Exception) {
            VonagePlugin.logInfo("Dispose session .onStop() error $e")
        }

        try {
            session?.unpublish(patientPublisher)
        } catch (e: Exception) {
            VonagePlugin.logInfo("Dispose session .unpublish() error $e")
        }
        try {
            session?.disconnect()
        } catch (e: Exception) {
            VonagePlugin.logInfo("Dispose session .disconnect() error $e")
        }

        doctorVideoView?.removeVideoFromContainer()
        patientVideoView?.removeVideoFromContainer()

        patientPublisher = null
        doctorSubscriber = null
        session = null
    }
```

**Comment by goncalocostamendes** [comment] 2023-12-29 15:45
@derekpitts28 I see the issue. There might indeed occur a race on the disposal of the session together with the publisher.

_Session.disconnect()_ is configured to disconnect internally any publisher(s) and subscriber(s).

I would recommend you changing the dispose method to:

`private fun dispose() {
        try {
            session?.disconnect()
        } catch (e: Exception) {
            VonagePlugin.logInfo("Dispose session .disconnect() error $e")
        }

        doctorVideoView?.removeVideoFromContainer()
        patientVideoView?.removeVideoFromContainer()

    }`

As previously mentioned, _Session.disconnect()_ will delete the publisher, which will trigger the callback _onStreamDestroyed()_. On that callback, the capturer can be safely stopped.

`
public void onStreamDestroyed(PublisherKit publisher, Stream stream) {
    try {
            patientPublisher?.onStop()
        } catch (e: Exception) {
            VonagePlugin.logInfo("Dispose session .onStop() error $e")
        }
}
`

Fell free to test it and give me feedback on it. 

Furthermore, I am adding a safety check on our SDK which will be released in 2.27.1 (mid January).

**Comment by derekpitts28** [comment] 2024-01-02 15:52
Thanks, let me implement what you mentioned above and see if that fixes this on the devices that were crashing. I will get back to you once I have a result. Thanks again! 🚀

**Comment by tinder-enginrumelioglu** [comment] 2024-01-02 21:25
@goncalocostamendes We are running into the same issue on our code base. Following your previous suggestion of not using `onStop` on the `publisher` seems to resolve the issue however I have some concerns. We create a `publisher` before creating a `session` because we want to give the user a preview of the video before joining the session. This sometimes leads to cases where a session is never created because the user decides to leave the activity without joining the chat, and our code is setup to call `publisher.onStop` since there is no `session` to call `disconnect` on. Do you see any issues with removing this `onStop` call (my immediate concern would be memory leaks)? Or should we wait for the `2.27.1` release that will address this issue?

**Comment by goncalocostamendes** [comment] 2024-01-03 11:22
@tinder-enginrumelioglu exactly, the session and the capturer are independent from one another. Scenarios such as publisher preview cannot blindly rely on the previous answer, because in such case the callback onStreamDestroyed() will never be triggered. We did not configure the session.disconnected() method to stop the capturer, because there might be use cases where the user does not want to stop the capturer.

In the mentioned scenario **Publisher preview, session never created and user leaves activity**, removing the call to `publisher.onStop` from the activity finalizer will lead to leaving the capturer running consuming CPU and the Android LED for the camera capturer will be green (ON), which may lead to privacy concerns by your clients. 

Possible suggestions are:
 - (case you never have more than one publisher) link the capturer `publisher.onStop` call to the publisher destructor (here you can remove `publisher.onStop` from `onStreamDestroyed()`);
 - leave the `publisher.onStop` call on the activity finalizer, but add a flag to validate if `publisher.onStop` was already triggered.

**Comment by derekpitts28** [comment] 2024-01-03 16:00
@goncalocostamendes Our tester reproduced the error with your recommended change regarding the .disconnect call.
Same error as before:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
	at com.opentok.android.Camera2VideoCapturer.stopDisplayOrientationCache(SourceFile:5)
	at com.opentok.android.Camera2VideoCapturer.destroy(SourceFile:12)
	at com.opentok.android.PublisherKit.a(SourceFile:2)
	at com.opentok.android.PublisherKit.z(SourceFile:1)
	at com.opentok.android.q.run(R8$$SyntheticClass:3)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by derekpitts28** [comment] 2024-01-03 17:27
@goncalocostamendes just an FYI for your suggestion for (2) above I cannot find a way to verify if onStopped was called it does not look like there is a public getter for isStopped as it is package private for the BaseVideoCapturer.

**Comment by goncalocostamendes** [comment] 2024-01-03 18:30
@tinder-enginrumelioglu @derekpitts28 _publisher.onStop_ can be triggered multiple times. It internally validates if it was already stopped. As such, for the question:

> @goncalocostamendes We are running into the same issue on our code base. Following your previous suggestion of not using `onStop` on the `publisher` seems to resolve the issue however I have some concerns. We create a `publisher` before creating a `session` because we want to give the user a preview of the video before joining the session. This sometimes leads to cases where a session is never created because the user decides to leave the activity without joining the chat, and our code is setup to call `publisher.onStop` since there is no `session` to call `disconnect` on. Do you see any issues with removing this `onStop` call (my immediate concern would be memory leaks)? Or should we wait for the `2.27.1` release that will address this issue?

You can leave both _publisher.onStop_ calls.

**Comment by goncalocostamendes** [comment] 2024-01-03 18:31
I will close the ticket since it seems the issue was resolved. Please open it if that is not the case.

**Comment by derekpitts28** [comment] 2024-01-03 19:07
@goncalocostamendes I don't think this was resolved unless you mean you have a fix for the later release. When trying to call onStop I get all sorts of errors unless you fixed those also. For example the situation where we want to keep the session open but stop the capturer, i call onStop and get a slew of errors:
```
W/MessageQueue(16897): Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): java.lang.IllegalStateException: Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue(16897): 	at android.os.Handler.enqueueMessage(Handler.java:786)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageAtTime(Handler.java:735)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageDelayed(Handler.java:705)
W/MessageQueue(16897): 	at android.os.Handler.post(Handler.java:435)
W/MessageQueue(16897): 	at android.media.ImageReader$HandlerExecutor.execute(ImageReader.java:1155)
W/MessageQueue(16897): 	at android.media.ImageReader.postEventFromNative(ImageReader.java:944)
W/MessageQueue(16897): Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): java.lang.IllegalStateException: Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue(16897): 	at android.os.Handler.enqueueMessage(Handler.java:786)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageAtTime(Handler.java:735)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageDelayed(Handler.java:705)
W/MessageQueue(16897): 	at android.os.Handler.post(Handler.java:435)
W/MessageQueue(16897): 	at android.media.ImageReader$HandlerExecutor.execute(ImageReader.java:1155)
W/MessageQueue(16897): 	at android.media.ImageReader.postEventFromNative(ImageReader.java:944)
W/MessageQueue(16897): Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): java.lang.IllegalStateException: Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue(16897): 	at android.os.Handler.enqueueMessage(Handler.java:786)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageAtTime(Handler.java:735)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageDelayed(Handler.java:705)
W/MessageQueue(16897): 	at android.os.Handler.post(Handler.java:435)
W/MessageQueue(16897): 	at android.media.ImageReader$HandlerExecutor.execute(ImageReader.java:1155)
W/MessageQueue(16897): 	at android.media.ImageReader.postEventFromNative(ImageReader.java:944)
W/MessageQueue(16897): Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): java.lang.IllegalStateException: Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue(16897): 	at android.os.Handler.enqueueMessage(Handler.java:786)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageAtTime(Handler.java:735)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageDelayed(Handler.java:705)
W/MessageQueue(16897): 	at android.os.Handler.post(Handler.java:435)
W/MessageQueue(16897): 	at android.media.ImageReader$HandlerExecutor.execute(ImageReader.java:1155)
W/MessageQueue(16897): 	at android.media.ImageReader.postEventFromNative(ImageReader.java:944)
W/MessageQueue(16897): Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): java.lang.IllegalStateException: Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue(16897): 	at android.os.Handler.enqueueMessage(Handler.java:786)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageAtTime(Handler.java:735)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageDelayed(Handler.java:705)
W/MessageQueue(16897): 	at android.os.Handler.post(Handler.java:435)
W/MessageQueue(16897): 	at android.media.ImageReader$HandlerExecutor.execute(ImageReader.java:1155)
W/MessageQueue(16897): 	at android.media.ImageReader.postEventFromNative(ImageReader.java:944)
W/MessageQueue(16897): Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): java.lang.IllegalStateException: Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread
W/MessageQueue(16897): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue(16897): 	at android.os.Handler.enqueueMessage(Handler.java:786)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageAtTime(Handler.java:735)
W/MessageQueue(16897): 	at android.os.Handler.sendMessageDelayed(Handler.java:705)
W/MessageQueue(16897): 	at android.os.Handler.post(Handler.java:435)
W/MessageQueue(16897): 	at android.media.ImageReader$HandlerExecutor.execute(ImageReader.java:1155)
W/MessageQueue(16897): 	at android.media.ImageReader.postEventFromNative(ImageReader.java:944)
```

**Comment by goncalocostamendes** [comment] 2024-01-04 10:37
@derekpitts28 just an FYI, the first error you mentioned `Handler (android.media.ImageReader$ListenerHandler) {982841} sending message to a Handler on a dead thread` is can also be caused by some event updating the UI from a background thread. At this moment, from our side, all _subscriberListener_ methods are configured to run on a background thread. We are updating this on 2.27.1

**Comment by goncalocostamendes** [comment] 2024-01-04 13:17
@derekpitts28 regarding your scenario **keep the session open but stop the capturer**, do you mean simply muting the video? Or unpublishing the publisher?

**Comment by derekpitts28** [comment] 2024-01-04 16:53
So in our case we have a session connected but we do not want to publish the users video yet. We only want to show a preview of the users view before they publish their video. If they decided to exit before publishing we need to close the publisher otherwise the capturer stays open and the user video indicator stays on. In almost all usages of onStop the app seems to run into the null object error eventually if not right away. I had my testers go through and use your recommended code for stopping the publisher ie using onStop and in almost all cases it crashes.

**Comment by goncalocostamendes** [comment] 2024-01-04 17:04
@derekpitts28 it seems to me you will need to wait for the 2.27.1 release which provides more safety checks when stopping the capturer and associated threads. In the mean time I will try to replicate that scenario and check if any other improvement can be made

**Comment by tinder-enginrumelioglu** [comment] 2024-01-04 17:30
I am running into the same issues that Derek is running into. It should be rather easy to duplicate with the following steps;
- Create a `Publisher` (no need to create a `Session`)
- Render the `View` from the `Publisher`
- Call `Publisher.onStop` and stop rendering the `View` when the activity is destroyed
- Observe that the app crashes a few seconds later

**Comment by janoonaj** [comment] 2024-01-29 17:07
+1 It is happening in production with 2.27.0  We start a call but we see black screen

**Comment by derekpitts28** [comment] 2024-01-29 18:05
> @derekpitts28 @janoonaj @tinder-enginrumelioglu The safest way to stop the camera is, instead of calling directly onStop() method, use `PublisherKit.setPublishVideo(boolean publishVideo)` which internally will call `onStop()` method, it will stop publishing video (will send black frames to the subscriber) and will release the capturer. To stop it simply call `publisher.setPublishVideo(false)`

@goncalocostamendes I believe this does not turn on the camera and the system green light stays on because vonage holds onto the camera object. I don't think this truely, stops/releases the camera and could cause users to think we are still using their camera when we are really not.

**Comment by goncalocostamendes** [comment] 2024-01-29 18:39
> > @derekpitts28 @janoonaj @tinder-enginrumelioglu The safest way to stop the camera is, instead of calling directly onStop() method, use `PublisherKit.setPublishVideo(boolean publishVideo)` which internally will call `onStop()` method, it will stop publishing video (will send black frames to the subscriber) and will release the capturer. To stop it simply call `publisher.setPublishVideo(false)`
> 
> @goncalocostamendes I believe this does not turn on the camera and the system green light stays on because vonage holds onto the camera object. I don't think this truely, stops/releases the camera and could cause users to think we are still using their camera when we are really not.

This is how we do it on our internal app, and I can validate that the `onStop()` method is called when `publisher.setPublishVideo(false)` is triggered. In addition, by calling `onStop()` directly instead of stop publishing video there may occur some errors, since you are trying to publish video that you are no longer capturing/rendering.

**Comment by derekpitts28** [comment] 2024-01-29 18:45
Can you verify does publisher.setPublishVideo(false) release the camera ie does the camera green light turn off on newer devices?

**Comment by goncalocostamendes** [comment] 2024-01-30 09:57
@derekpitts28 yes, it turns off the green LED

**Comment by bricepowell** [comment] 2024-01-31 22:22
this worked for me!

> > > @derekpitts28 @janoonaj @tinder-enginrumelioglu The safest way to stop the camera is, instead of calling directly onStop() method, use `PublisherKit.setPublishVideo(boolean publishVideo)` which internally will call `onStop()` method, it will stop publishing video (will send black frames to the subscriber) and will release the capturer. To stop it simply call `publisher.setPublishVideo(false)`
> > 
> > 
> > @goncalocostamendes I believe this does not turn on the camera and the system green light stays on because vonage holds onto the camera object. I don't think this truely, stops/releases the camera and could cause users to think we are still using their camera when we are really not.
> 
> This is how we do it on our internal app, and I can validate that the `onStop()` method is called when `publisher.setPublishVideo(false)` is triggered. In addition, by calling `onStop()` directly instead of stop publishing video there may occur some errors, since you are trying to publish video that you are no longer capturing/rendering.

can confirm this worked for me. Thanks!

**Closed** 2024-02-01 13:22 UTC
