### ISSUE TITLE
After Android Studio update to 4.2.2 -status code 403 from server

### ISSUE THREAD

**Issue by gauravbvi17** [opentok/opentok-android-sdk-samples#394] opened 2021-07-09 04:01 UTC
Could not GET 'http://tokbox.bintray.com/maven/com/opentok/android/v3/opentok-android-sdk-v3/3.1.3/opentok-android-sdk-v3-3.1.3.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

**Comment by adrienrx** [comment] 2021-07-09 10:49
bintray has closed, you need to remove the repo tokbox.bintray.com and replace it by mavenCentral(). See here https://tokbox.com/developer/sdks/android/#creating-your-own-app-using-the-opentok-android-sdk

**Comment by baole** [comment] 2021-07-09 13:10
Same for me, `opentok-android-sdk-v3 3.0.3` artifact doesn't exist on mavenCentral().

**Comment by adrienrx** [comment] 2021-07-14 12:33
https://support.tokbox.com/hc/en-us/articles/360059402811-Android-SDK-available-through-maven-central

**Comment by baole** [comment] 2021-07-14 12:37
From https://support.tokbox.com/hc/en-us/articles/360059402811-Android-SDK-available-through-maven-central
> If you are using a version 2.16.x or older, please note that those old SDKs could depend on additional binaries that may not be available in Maven. We recommend that you download locally the required binaries to prevent any interruption to your development and testing processes but also plan to migrate to the latest version of the SDK. The latest versions include major performance improvements and bug fixes.

The recommendation to dowload locally seems awkward. Gradle warns if you put a .aar locally. If you put it in maven's cache, it doesn't work with CI tools.

**Comment by adrienrx** [comment] 2021-07-14 12:38
As a temporary solution, I have hosted that missing lib on a personal maven server.

**Comment by tedyk** [comment] 2021-07-23 14:58
@adrienrx , I have a project that uses Salesforce SDK, which has a dependency on "opentok-android-sdk:2.16.3", which in turn seems to depends on "opentok-android-sdk-v3", version 3.1.3 - the latest version available in MavenCentral is 2.20.1, and I'm unable to find "opentok-android-sdk-v3", version 3.1.3 anywhere. 

Would you know a place where I can download that while I wait for Salesforce to update to the latest opentok sdk?

**Comment by paulinabls** [comment] 2021-07-30 16:12
Same here, we're heavily dependent on opentok-android-sdk-v3. :/ 

@adrienrx  would it possible to share either a link or just an .aar file? 🙏

**Comment by xoliver** [comment] 2021-08-02 10:44
@adrienrx I second @paulinabls 's call

**Comment by klapperkopp** [comment] 2021-08-04 22:30
Just FYI, we are working on this and will update here once we have a solution that is confirmed working and including simple instructions.

**Comment by dharamvirsaini** [comment] 2021-08-06 09:09
I just downloaded the 2.16.1 .aar file from here:- https://s3.amazonaws.com/artifact.tokbox.com/rel/android-sdk-webrtc/opentok-android-sdk-2.16.1.zip and I was able to build and run the basic sample. Hope the below steps would help in resolving the v3 dependencies issue:-

- In Android Studio, create libs folder under app level directory and paste the .aar file in it.

- Modify the app level's build.gradle file and add implementation fileTree(include: ['*.aar'], dir: 'libs')  inside the dependencies section. Please see the snapshot of what modified build.gradle file looks like.

- Clean and build the project and it should work.

**Comment by tedyk** [comment] 2021-08-23 16:45
I tried the approach from @dharamvirsaini , but wasn't able to get a successful build. My dependency is on opentok-android-sdk-2.16.3, which I downloaded from https://s3.amazonaws.com/artifact.tokbox.com/rel/android-sdk-webrtc/opentok-android-sdk-2.16.3.zip, and updated the build.gradle to use the local aar file. Clean build still resulted in a failure that reported the need for v3 library file:

```
[10:39:09]: ▸ FAILURE: Build failed with an exception.
[10:39:09]: ▸ * What went wrong:
[10:39:09]: ▸ Could not resolve all files for configuration ':app:releaseCompileClasspath'.
[10:39:09]: ▸ > Could not find com.opentok.android.v3:opentok-android-sdk-v3:3.1.3.
[10:39:09]: ▸ Required by:
[10:39:09]: ▸ project :app > com.opentok.android:opentok-android-sdk:2.16.3
```

**Comment by klapperkopp** [comment] 2021-08-30 09:02
I have tried @dharamvirsaini's solution above and it works for me. See screenshot for my config with relevant sections marked in blue.
<img width="1420" alt="Bildschirmfoto 2021-08-30 um 11 59 32" src="https://user-images.githubusercontent.com/11021127/131314613-585cff79-99ee-4e83-bd41-fdcd38a65f64.png">
If this still doesn't work and your build.gradle files look differently, maybe it's possible to share them?

**Comment by ajiehatajie** [comment] 2021-09-23 05:00
same issue

**Comment by adrienrx** [comment] 2021-11-09 13:47
Oh sorry I missed this. Do you guys still need it ? Very very late to the party

**Comment by baole** [comment] 2021-11-09 14:04
Yes, I do

**Comment by adrienrx** [comment] 2021-11-10 10:27
[opentok-android-sdk-v3-3.1.3.zip](https://github.com/opentok/opentok-android-sdk-samples/files/7511917/opentok-android-sdk-v3-3.1.3.zip)

**Comment by baole** [comment] 2021-11-10 11:19
@adrienrx thank you! I meant a mavenized version.

**Comment by adrienrx** [comment] 2021-11-10 11:44
maven { url 'https://github.com/adrienrx/legacy-otk/raw/master'}

Let me know if this helps

**Comment by hithaprani-pop** [comment] 2022-01-05 10:43
@adrienrx can you provide files for "opentok-android-sdk-v3:3.1.5"

**Comment by adrienrx** [comment] 2022-01-05 15:17
Hmm I don't have this version on my local unfortunately @hithaprani-pop

**Closed** 2022-10-26 21:57 UTC
