### ISSUE TITLE
Android device shows microphone is actively being used even though session is paused and audio is disabled

### ISSUE THREAD

**Issue by iori57** [opentok/opentok-android-sdk-samples#419] opened 2022-03-31 02:56 UTC
1) Start publishing to a session, notice that Android OS now reports that camera and microphone is being used by the app, which is fine.

![image](https://user-images.githubusercontent.com/5056279/160966913-bb82d6bc-ee49-4073-924e-ff9551702f56.png)

2) Call session.onPause() followed by publisher.publishAudio = false. 
2) (Optional) Move application into background by pressing Home button. 
3) Android OS indicates that camera is no longer being used, but microphone is still being used by the application.

![image](https://user-images.githubusercontent.com/5056279/160966962-53f9d027-f078-43ae-92be-3b5e487459d5.png)

Although it does not affect usability of the app it is bad in terms of user privacy perspective - the user might think the app is still recording audio while it is in background, which is scary.

Is there other methods I can call to turn off the microphone access totally, just like the camera?

**Comment by iori57** [comment] 2023-04-23 00:59
Thanks for following up with this issue! Can you expedite this? It has just became a bigger problem now that our app has implemented [network bandwidth test](https://github.com/opentok/opentok-network-test) that runs in the background following the sample provided. When the network test runs (with publishAudio set to false), it shows that the microphone is being accessed, even when user is not making a call, which is scary in terms of user's privacy as user may thought our app is secretly recording audio in the background.

**Comment by v-kpheng** [comment] 2023-04-28 19:47
@iori57, we're looking into it.

**Comment by goncalocostamendes** [comment] 2023-05-02 11:05
@iori57 we have identified the root cause of the issue. Due to your urgency, if you are using a custom audio driver you can easily fix it yourself. I can guide you on it. Meanwhile we are working on a solution that can be applicable to our default audio driver.

**Comment by iori57** [comment] 2023-05-02 12:07
That is good news! I am using the default audio driver so will wait for the fix. Thank you!

**Comment by beHaze** [comment] 2023-07-20 20:46
Fixed in 2.25.3 release.

**Closed by beHaze** 2023-07-20 20:46 UTC

**Comment by ss-stanislavsky** [comment] 2023-11-21 19:20
> @iori57 we have identified the root cause of the issue. Due to your urgency, if you are using a custom audio driver you can easily fix it yourself. I can guide you on it. Meanwhile we are working on a solution that can be applicable to our default audio driver.

Hello, could you please guide me how to fix this issue on old version of library with custom AudioDevice? Thanks!

**Comment by goncalocostamendes** [comment] 2023-11-28 17:52
@ss-stanislavsky the fix ended up being only on our internal lib, so with the custom AudioDevice sample the LED should get disabled correctly.

Please guarantee you target version 2.25.3 or higher. If you have any issues please answer back
