### ISSUE TITLE
AdvancedAudioDevice bluetooth with LG V30

### ISSUE THREAD

**Issue by lparnes1** [opentok/opentok-android-sdk-samples#410] opened 2021-12-23 21:15 UTC
I have an LG V30 running Android 9 and a Samsung Galaxy Tab A running Android 8.1.  They can both work with bluetooth headphones without using the AdvancedAudioDevice.  When using the AdvancedAudioDevice, the Samsung works, but the LG doesn't although it appears to go through the same code path up to connecting to bluetooth, and it doesn't disconnect.  Changing the Android audio stream to use didn't make any difference either.

I have also gone through the code and changed the deprecated things in AdvancedAudioDevice, requestAudioFocus, new AudioTrack, and abandonAudioFocus to the 'proper' code, and it didn't change anything - the LG wouldn't push sound through the bluetooths before or after, and the Samsung could.  After searching around, I could find LG V30 bluetooth has some issues, but I also found issues with Samsung Galaxy Tabs.

Any ideas or is there anything specific I could provide for you?

**Comment by v-kpheng** [comment] 2022-10-19 21:59
Thanks, @lparnes1, for letting us know about the issue.

A lot of bluetooth improvements have been made since this was first filed, so I'm going to close this issue.  If this issue can still be reproduced on the current version of the SDK, please let us know.  Thanks!

**Closed by v-kpheng** 2022-10-19 21:59 UTC
