### ISSUE TITLE
Phone call interruption freezes video feeds [SDK 2.20.1]

### ISSUE THREAD

**Issue by ravi-dexcare** [opentok/opentok-android-sdk-samples#409] opened 2021-12-16 18:30 UTC
When in a session if the user gets a call and if he attends it while coming back video feeds is frozen.

Tested on:
Google Pixel4 
Android 12
SDK version: 2.20.1

**Comment by v-kpheng** [comment] 2022-09-28 01:45
@ravi-dexcare, thank you for filing this issue.  Can you please see if this is still reproducible on the latest release?

Closing, since 2.20 is no longer supported.

**Closed by v-kpheng** 2022-09-28 01:45 UTC
