### ISSUE TITLE
Session.disconnect crash

### ISSUE THREAD

**Issue by DanyGZ** [opentok/opentok-android-sdk-samples#253] opened 2019-10-17 04:09 UTC
Hi, in version 2.16.2 calling Session.disconnect() is throwing java.util.ConcurrentModificationException. 

Pre-conditions: 
* We are using the SDK to create a video-conference between multiple users. 
* We have 3 (or more) users (different devices) connected to the conference.
* In any device, call Session.disconnect()

App is crashing while SDK is calling `clearPublishersAndSubscribers` method

**Comment by edwardbrosens** [comment] 2019-10-27 10:46
> Hi, in version 2.16.2 calling Session.disconnect() is throwing java.util.ConcurrentModificationException.
> 
> Pre-conditions:
> 
> * We are using the SDK to create a video-conference between multiple users.
> * We have 3 (or more) users (different devices) connected to the conference.
> * In any device, call Session.disconnect()
> 
> App is crashing while SDK is calling `clearPublishersAndSubscribers` method

Use this version, it's stable.
```
implementation 'com.opentok.android:opentok-android-sdk:2.14.+'
```
Devt eam is a bit slow in fixing this.

**Comment by romanpozd-tg17** [comment] 2019-11-17 12:01
+1

**Comment by marinaserranomontes** [comment] 2019-11-18 11:54
Hi,

A patch to fix it will be released in v2.16.3 soon.

Best,
Marina

**Comment by janosvajda** [comment] 2020-05-15 03:05
Hi,

I use 2.16.4 but this bug still exists. I got this error message today:


2020-05-15 03:58:14.498 19614-19614/ E/AndroidRuntime: FATAL EXCEPTION: main
    Process:    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.opentok.android.v3.Session.clearPublishersAndSubscribers(Session.java:688)
        at com.opentok.android.v3.Session.disconnect(Session.java:319)
        at com.opentok.android.Session.disconnect(Session.java:903)
        at com.qdoctor.android.qhealth.Consultation$7.onSignalReceived(Consultation.java:534)

when code calls session.disconnect();

thanks,
Janos

**Comment by adrienrx** [comment] 2020-05-18 10:15
Same here java.util.ConcurrentModificationException at java.util.ArrayList$Itr.next(ArrayList.java:860) at com.opentok.android.v3.Session.clearPublishersAndSubscribers(Session.java:688) at com.opentok.android.v3.Session.disconnect(Session.java:319) at com.opentok.android.Session.disconnect(Session.java:903) 

Version: 2.16.3

Is there a way to avoid this issue whilst we wait for a fix?

**Comment by robjperez** [comment] 2020-05-18 12:46
@adrienrx @janosvajda Can you try with the new 2.17 version?

it should be fixed there

**Comment by janosvajda** [comment] 2020-05-18 12:50
@robjperez Yes, but that version has different issues so we do not use it on production.

**Comment by robjperez** [comment] 2020-05-19 10:35
@janosvajda thanks for the message,
which issues are you seeing in 2.17?

**Comment by janosvajda** [comment] 2020-05-19 10:47
Hi, @robjperez I tried to upgrade our Android app twice but I failed. Because of losing video on the publisher's side.  I try to describe it a bit more detailed. So, when I tried to use 2.17 in the app (this is the subscriber) then the publisher did not see the video coming from the mobile. This publisher's part of our system is in the browser (Chrome). And, this side uses OpenTok 2.16.6 JavaScript SDK. 

So, this is why I have not done the upgrade of our Android app from com.opentok.android:opentok-android-sdk:2.16.4 to 2.17.

**Comment by adrienrx** [comment] 2020-05-26 12:40
Same here, moving to 2.17 doesn't help since it's introducing new issues.

**Comment by edwardbrosens** [comment] 2020-05-26 13:15
> Same here, moving to 2.17 doesn't help since it's introducing new issues.

What issues?

**Comment by janosvajda** [comment] 2020-05-26 13:19
@edwardbrosens I described the issue in my previous comment what I experienced when I upgraded Tokbox SDK... I think @adrienrx created my comment and he experienced the same what I did.

**Comment by adrienrx** [comment] 2020-05-28 07:54
@janosvajda Same issue here, had an issue on the previous sdk, upgraded to 2.17 hopping that it would fix it. Ended up breaking other features...

**Comment by janosvajda** [comment] 2020-05-28 08:16
@adrienrx Yeah, 2.17 Android Tokbox SDK seems to be buggy so We decided that We do not upgrade our app to this version. I am waiting for the next version and if It will be buggy as well then I will contact with the customer service.

**Comment by robjperez** [comment] 2020-05-28 14:00
Hi!
Can you please open an issue with the problem you are seeing in 2.17?
Can you reproduce them with Basic Video Chat sample?

**Comment by robjperez** [comment] 2020-06-03 14:20
Going to close the issue due to inactivity, please reopen or report a new issue if you still have problems

**Closed by robjperez** 2020-06-03 14:20 UTC

**Comment by mhdHasanAlgnadi** [comment] 2021-06-24 10:18
I still have same issue on swift .. actually I build it on flutter app and in AppDelegate when I call session?.disconnect the app crash and send '-[__NSDictionaryM longLongValue]: unrecognized selector sent to instance 0x283e4c080
