### ISSUE TITLE
Audio capture is not initialized 44100

### ISSUE THREAD

**Issue by rameshk5085** [opentok/opentok-android-sdk-samples#221] opened 2019-05-21 13:23 UTC
after publishing the publisher to session,i'm getting error "Audio capture is not initialized 44100".but when i enable pubilshaudio property ,StreamCreated event is invoked and subscriber is able to get the publisher view but audio is not working.

**Comment by robjperez** [comment] 2019-05-22 14:54
HI @rameshk5085 can you provide us with some details.

Which sample code are you using?
Are you using a custom audio driver?
Are you using 2.16? 2.16 came with some improvements in the bundled audio driver.

Thanks!

**Comment by rameshk5085** [comment] 2019-05-27 05:33
Hi @robjperez 
Xamarin OpenTok Android -v2.13.0,
Visual Studio 2019 -v16.1.0,
Are you using a custom audio driver? - No
i'm using Multiparty-ConstraintLayout sample.

Thanks.

**Comment by robjperez** [comment] 2019-05-27 09:11
Can you try if it is reproducible with 2.16?

**Comment by rameshk5085** [comment] 2019-05-28 07:08
when i tried with 2.16 version in visual studio 2019.i'm getting below compiler error.

Error : java/lang/String;)Lorg/webrtc/VideoDecoder;: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.VideoDecoderFactory.createDecoder : (Ljava/lang/String;)Lorg/webrtc/VideoDecoder;		

after changing min-sdk-version to 27 then also error occur.

**Comment by robjperez** [comment] 2019-05-28 15:45
Starting with 2.16, you need to add Java 8 compiler support to the project,

See: https://github.com/opentok/opentok-android-sdk-samples/blob/master/Basic-Video-Chat/app/build.gradle#L16

Please check that your xamarin project is setting that correctly.

**Comment by robjperez** [comment] 2020-07-13 13:49
We did some changes in 2.17.1 around the audio driver initialization. 
I'm going to close this issue since it doesn't have recent activity. 

Please reopen if necessary

**Closed by robjperez** 2020-07-13 13:49 UTC
