### ISSUE TITLE
Some delays observing while screen share android

### ISSUE THREAD

**Issue by vmeditab** [opentok/opentok-android-sdk-samples#477] opened 2023-09-20 06:15 UTC
I am feeling some delays while sharing screen from tablet to android mobile.

Below is my code,

    `class CustomVideoCapturer : BaseVideoCapturer() {
     companion object {
        const val TAG = "CustomVideoCapturer"

        const val pixelFormat = ABGR;
     }

    private var width: Int = 640
    private var height: Int = 480
    private var isCapturing: Boolean = false

    override fun init() {
        Log.e(TAG, "On Init")
    }

    override fun onResume() {
        Log.e(TAG, "On Resume")
    }

    override fun onPause() {
        Log.e(TAG, "On Pause")
    }

    override fun getCaptureSettings(): CaptureSettings {
        val captureSettings = CaptureSettings()
        captureSettings.width = width
        captureSettings.height = height
        captureSettings.fps = 7
        captureSettings.expectedDelay = 0

        return captureSettings
    }

    override fun startCapture(): Int {
        Log.e(TAG, "Start Capture")
        return 0
    }

    override fun stopCapture(): Int {
        Log.e(TAG, "Stop Capture")
        return 0
    }

    override fun isCaptureStarted(): Boolean {
        return isCapturing
    }

    override fun destroy() {
        Log.e(TAG, "Destroy")
    }

    fun sendFrame(imageBuffer: ByteBuffer, imageWidth: Int, imageHeight: Int) {
        provideBufferFrame(imageBuffer, pixelFormat, imageWidth, imageHeight, 0, false)
    }

}`

And below is screen sharing code,

            ` screenPublisher =
                Publisher.Builder(this@NewTelevisitActivity).name(jsonObject.toString())
                    .capturer(customVideoCapturer).build()
            screenPublisher?.publisherVideoType =
                PublisherKit.PublisherKitVideoType.PublisherKitVideoTypeScreen
            screenPublisher?.publishVideo = true
            screenPublisher?.publishAudio = publisher?.stream?.hasAudio() == true
            screenPublisher?.audioFallbackEnabled = false
            screenPublisher?.setPublisherListener(this)
            session?.publish(screenPublisher)`

As you can see in attached video, while I am expanding/collapsing framelayout, the screen shared video will be shown in black and if I will do any action in tab the screen shared video will be shown again or the frames will be again visible withing 10 to 12 seconds. Please suggest me if any kind of resolution issue or something else.

https://github.com/opentok/opentok-android-sdk-samples/assets/79642753/c3e14db2-f932-484c-afe2-a1e358f09772

**Comment by vmeditab** [comment] 2023-10-04 10:47
Hello @v-kpheng, is there any update regarding this issue?

**Comment by goncalocostamendes** [comment] 2023-10-18 14:51
@vmeditab I have noted we were not providing a Kotlin sample for screen sharing using a WebViewer so I have created one. At the moment it was not merged yet, but you can have a look at it in https://github.com/opentok/opentok-android-sdk-samples/pull/486.

In regards to your specific problem, I see you have setted the video type of the published
stream to _PublisherKitVideoType.PublisherKitVideoTypeScreen_, which optimizes the video encoding for
screen sharing. You have also setted a low frame rate, which is advised, however it seems you have not provided the entire code of your _CustomVideoCapturer_ class:
 - With each periodicity is _sendFrame()_ called? 
 - When do you start sharing the screen? I see _startCapture()_ is not doing anything.

Also your issue is a bit more complex than only sharing the screen, since you are sharing the screen from your tablet to your Android mobile, which is where you expand/collapse the frameLayout. It is possible when these events are triggered, the code is not being handled correctly.

Could you share more code of your project?

**Comment by vmeditab** [comment] 2023-10-19 06:24
Hey @goncalocostamendes ,

Please see my code below for activity where I am handling expand collapse framelayout. I am using recyclerview for below layout of the main view and simply used `notifyItemchanged` methods while pin/unpin.

**MainActivity.kt**

```
//This method while sending the frame
    override fun sendFrame(imageBuffer: ByteBuffer, width: Int, height: Int) {
        customVideoCapturer?.sendFrame(imageBuffer, width, height)
    }

// This is used for swapping framelayouts
      attendeesAdapter =
            AttendisAdapter(this@NewTelevisitActivity, object : AddViewDetailClickListener {
                override fun onSwapViews(
                    container: NewSubscriberContainer?, index: Int
                ) {
                    binding.fmSubscriber.restore()
                    subscriberContainer?.let { mSubscribers.set(index, it) }
                    attendeesAdapter.notifyItemChanged(index)
                    subscriberContainer = container

                    updateMainView()
                }
            })

//This is used for update the main large view which is showing in upper side

    private fun updateMainView() {
        binding.fmSubscriber.removeAllViews()
        subscriberContainer?.subscriber?.let {
            it.view.removeSelf()
            (it.view as GLSurfaceView).setZOrderOnTop(false)
            // https://medpharm.atlassian.net/browse/PP-608
            // Point - 2
            // set ratio for display for web screen share
            if (subscriberContainer?.userDetails?.platform == "web" && subscriberContainer?.userDetails?.designation_desc == "Screen") {
                // PP-608 (Reopen Point - 1)
                // added zoom in zoom out
                val layoutParams = FrameLayout.LayoutParams(
                    binding.fmSubscriber.width,
                    (binding.fmSubscriber.height / 3.5).toInt()
                )
                it.view.layoutParams = layoutParams
                layoutParams.gravity = Gravity.CENTER
                binding.fmSubscriber.addView(it.view)

                it.setStyle(
                    BaseVideoRenderer.STYLE_VIDEO_SCALE,
                    BaseVideoRenderer.STYLE_VIDEO_FIT
                )
            } else {
                binding.fmSubscriber.addView(it.view)
                it.setStyle(
                    BaseVideoRenderer.STYLE_VIDEO_SCALE,
                    if (subscriberContainer?.userDetails?.platform == "tab") BaseVideoRenderer.STYLE_VIDEO_FILL else BaseVideoRenderer.STYLE_VIDEO_FIT
                )
            }
            binding.fmSubscriber.enableTouch(subscriberContainer?.userDetails?.designation_desc == "Screen")
            binding.rlVideo.visibility = if (it.stream?.hasVideo() == true) GONE else VISIBLE
            setVideoListener(it, binding, subscriberContainer)
            setStreamListener(it, binding)
            binding.imgPinnedMute.visibility = VISIBLE
            // PP-745
            // update mic icon of subscriber for main view
            binding.imgPinnedMute.setImageResource(if (it.stream?.hasAudio() == true) R.drawable.ic_pin_mic else R.drawable.ic_pin_mute)
        }
        subscriberContainer?.publisher?.let {
            it.view.removeSelf()
            // PP-608 (Reopen Point - 1)
            // added zoom in zoom out
            binding.fmSubscriber.addView(it.view)
            it.setStyle(
                BaseVideoRenderer.STYLE_VIDEO_SCALE,
                BaseVideoRenderer.STYLE_VIDEO_FILL
            )
            binding.rlVideo.visibility = if (it.stream?.hasVideo() == true) GONE else VISIBLE
            binding.imgPinnedMute.visibility = GONE
            binding.fmSubscriber.enableTouch(false)
        }
        binding.tvSubscriber.text = subscriberContainer?.name
        binding.tvShortName.text =
            ConstTM.getShortName(subscriberContainer?.userDetails?.role_name)
    }
```

**Comment by v-kpheng** [comment] 2023-11-06 14:04
@vmeditab, a new sample app was created: https://github.com/opentok/opentok-android-sdk-samples/tree/main/Screen-Sharing-Kotlin.  Can you still reproduce with that?

**Closed** 2023-12-06 19:05 UTC
Labels: investigating
