### ISSUE TITLE
Camera preview showing black screen when Resume

### ISSUE THREAD

**Issue by gitanshubatra239** [opentok/opentok-android-sdk-samples#440] opened 2022-10-20 03:26 UTC
I've taken help from "Basic-Video-Capturer-Camera-Camera2-java" repo. I am getting issue when i send the app to the background, and resuming the app again. I am getting black screen shown on the publisher view.

code reference:
 publisher = new Publisher.Builder(context)
                    .capturer(new CameraCaptureClass(context))
                    .build();

and I've used "MirrorVideoCapture" class as my CameraCaptureClass. 
Please let me know if any other information is required to look into this issue.

**Comment by gitanshubatra239** [comment] 2022-10-26 05:25
Hey, please update

**Comment by v-kpheng** [comment] 2022-10-26 21:46
Thanks, @gitanshubatra239, for filing this issue.  Some key details are missing, however, which may make root cause difficult.  I'm going to close this issue as a result.  Can you please refile using the `Bug report` template?  It asks you some critical details which will help us immensely.

Thanks!

**Closed by v-kpheng** 2022-10-26 21:46 UTC
