### ISSUE TITLE
Native thread exiting without having called DetachCurrentThread

### ISSUE THREAD

**Issue by shahalRahman** [opentok/opentok-android-sdk-samples#313] opened 2020-10-09 14:54 UTC
Using Android OpenTok SDK v2.18.0

After ending the call by calling 
`
mSession.unsubscribe(mSubscriber);
mSession.unpublish(mPublisher);
mSession.disconnect();
`

In the Logcat i can see this warning,
W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[57,tid=2791,Native,Thread*=0x55974d2880,peer=0x12c75e20,"Thread-218"]

**Comment by igorwojda** [comment] 2021-02-17 11:09
I am unable to reproduce this.
Can you provide a sample project?

**Comment by igorwojda** [comment] 2021-03-01 11:23
We are unable to reproduce this, so I will close it for now.

**Closed by igorwojda** 2021-03-01 11:23 UTC
