### ISSUE TITLE
CustomVideoCapturerCamera2$Camera2Exception: Start Capture called before init successfully completed

### ISSUE THREAD

**Issue by Geremp** [opentok/opentok-android-sdk-samples#290] opened 2020-07-03 09:11 UTC
Hello,

Some times when i am lauching my activity, i get this error : 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.visitemonappart.vma, PID: 19754
    com.visitemonappart.vma.vonage.CustomVideoCapturerCamera2$Camera2Exception: Start Capture called before init successfully completed.
        at com.visitemonappart.vma.vonage.CustomVideoCapturerCamera2.startCapture(CustomVideoCapturerCamera2.java:388)
        at com.opentok.android.PublisherKit.lambda$onCaptureStartJNI$10$PublisherKit(Unknown Source:4)
        at com.opentok.android.-$$Lambda$PublisherKit$QEqpFEsDXqjsQVtUKJsYGmlG8Bk.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

Here what i do :  
```java
protected void onCreate(Bundle savedInstanceState) {
  first_launch = true;
}

protected void onResume() {
        super.onResume();

        if(first_launch == true) //Detect if we launch for the first time this activity (and not resume it after background)
        {
            mPublisherViewContainer = (FrameLayout)findViewById(R.id.publisher_container);
       
            mPublisher = new Publisher.Builder(VonageActivity.this)
                    .name("En Direct !")
                    .capturer(new CustomVideoCapturerCamera2(VonageActivity.this, Publisher.CameraCaptureResolution.HIGH,Publisher.CameraCaptureFrameRate.FPS_30))
                    .build();
            mPublisher.setPublisherListener(this);

            mPublisher.getRenderer().setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE,
                    BaseVideoRenderer.STYLE_VIDEO_FILL);

            mPublisher.setCameraId(backCameraId);
            mPublisherViewContainer.addView(mPublisher.getView());
        }

     }
```

Before, i was initialize my publisher on the oncreate.
When i see this error, i put it on method onRseume.

What is the best way to launch a preview when the activity is launch ?

**Comment by Geremp** [comment] 2020-07-03 10:34
I see that happens on your example too.
My phone : Honor lite 20
Android 10

**Comment by robjperez** [comment] 2020-07-10 15:59
Thanks for reporting @Geremp 

Why are you using a custom capturer?
Are you using the same code that we have in the Custom Video Driver sample?

Does that happen in the Basic Video Chat without using a custom capturer.

**Comment by Geremp** [comment] 2020-07-10 16:21
Hello,

I try your custom video driver example. And I get the same error. And black screen for the publisher. 

I never get this error on basic chat example without using custom capturer. 

Cordialement,

Jérémie PERERA

**Comment by robjperez** [comment] 2020-07-13 14:24
Hi,

I tried to reproduce the error but with no luck.

I noticed that in your code you were never setting `first_launch=false`.
Also, I think `onResume` might not be the right place to put this code. Since it can be called multiple times and you could create multilple publisher instances.

Can you please update your code and try again?

Thanks!

**Comment by Geremp** [comment] 2020-07-15 14:34
Hello @robjperez ,

I test your Custom-Capturer-Camera2 example without any change on my part.
I test to reproduce this "bug ?" by relaunch your app multiple time.
This "bug ?" not happens everytime.

after 5/10 relaunch, i get a black screen one the phone (publisher) image1.jpg : 
![image1](https://user-images.githubusercontent.com/6321146/87557957-d0590b00-c6b8-11ea-80a4-82057d88bc53.jpg)

And on the opentok playground you can see that my publisher is connected but no image image2.png : 
![image2](https://user-images.githubusercontent.com/6321146/87557816-b15a7900-c6b8-11ea-8537-e9e7608ede44.png)

I attach the log of android studio : 
[android_studio_log.txt](https://github.com/opentok/opentok-android-sdk-samples/files/4925899/android_studio_log.txt)

I didn't get the previous error this time, but black screen, and video not send.

I hope the log file would help :)

**Comment by igorwojda** [comment] 2021-01-14 14:11
1. Regarding an original `Camera2Exception` issue I was not able to reproduce this - if this still is an issue, please provide a sample project and information about the affected devices (Device model, Android version).
2. Regarding the publisher not publishing the stream - there is a separate issue to cover its problem https://github.com/opentok/opentok-android-sdk-samples/issues/324

**Comment by igorwojda** [comment] 2021-01-27 09:51
It's have been a while, so I will close this issue for now. Feel free to reopen it if you still need help on this.

**Closed by igorwojda** 2021-01-27 09:51 UTC
