### ISSUE TITLE
Calling crashes on Android 12 with error regarding BLUETOOTH_CONNECT permission. Log trace in comments

### ISSUE THREAD

**Issue by salmanjawedfolio** [opentok/opentok-android-sdk-samples#405] opened 2021-10-21 07:24 UTC

**Comment by v-kpheng** [comment] 2022-10-07 23:00
Thanks, @salmanjawedfolio, for filing this issue.

Closing, since this has been fixed by newer versions of the SDK.  If you're still able to reproduce using the most recent version, please file another issue.  Thanks!

**Closed by v-kpheng** 2022-10-07 23:00 UTC
