### ISSUE TITLE
Can't use Android App Bundle

### ISSUE THREAD

**Issue by peterMonteer** [opentok/opentok-android-sdk-samples#230] opened 2019-06-11 15:00 UTC
When building the apk/app bundle, the OpenTok dependency creates a folder called "lib" in the root directory, with data referencing various abis versions. This lib folder conflicts with the app bundle creation, and prevents it. 
I've been trying to circumvent this for a while but found no solution, are you guys working to solve this? Is there any workaround?

**Comment by robjperez** [comment] 2019-07-15 15:35
Hi @peterMonteer 

Can you give us more details about the problem?

Just tried to repro it with Basic-Video-Chat sample and I could build the apk without any issues.

**Comment by peterMonteer** [comment] 2019-07-15 15:56
Hi!
I can also build the apk just fine, but I can't build an app bundle.
The opentok sdk creates a lib folder when assembling the app ( if you analyze the apk you just build, you will see it at the top level I think), and this 'lib' folder conflicts with building an app bundle.

**Comment by robjperez** [comment] 2019-07-15 16:40
Hi again,

I'm not sure about the problem, if you look at the android documentation: https://developer.android.com/guide/app-bundle/

lib/ folder is where all native libraries should be.

I've tried to build a bundle with Basic-Video-Chat sample and it looks like I can get the `app.aab` file fine.

**Comment by peterMonteer** [comment] 2019-07-16 10:28
Well maybe I missed a step in some configuration I don't know. 
This is the error message I get everytime I try to build an app bundle:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageMyAppDebugBundle'.
> 1 exception was raised by workers:
  com.android.tools.build.bundletool.exceptions.BundleFileTypesException$FileUsesReservedNameException: File 'root/lib/x86_64-MacOSX-gpp/jni/libjunixsocket-native-2.0.4.jnilib' uses reserved file or directory name 'lib'.
```

**Comment by robjperez** [comment] 2019-07-17 08:55
That's strange, also, we don't really use anything by the path 
`x86_64-MacOSX-gpp/jni/libjunixsocket-native-2.0.4.jnilib`

It doesn't look that this is related to the SDK or the samples.

I'm going to close the issue, but please reopen it if you find that the problem is related with Opentok.

Thanks!

**Closed by robjperez** 2019-07-17 08:55 UTC

**Comment by peterMonteer** [comment] 2019-07-17 10:12
Image of APK analyzer

![image](https://user-images.githubusercontent.com/28009502/61367415-7514f280-a883-11e9-8244-78081860ff56.png)

If I exclude the folder `x86_64-MacOSX-gpp` when trying to build the app bundle, the same error that I posted before points to one of the folders which contains opentok files ( for example : x86/libopentok.so)
