### ISSUE TITLE
Publisher video is not stream after session reconnection

### ISSUE THREAD

**Issue by NataliiaZarudna** [opentok/opentok-android-sdk-samples#280] opened 2020-05-07 15:14 UTC
Please check the issue that appeared after update to 2.17.0 on Android 5.

TC:
1. Connect to session
2. Add publisher to session
3. Disconnect from session
4. Connect to session
5. Add publisher to session

ER. Publisher video is streamed  
AR. Publisher video is shown as black view.

Please check sample created based on Basic-Video-Chat sample: https://github.com/NataliiaZarudna/OpenTokPublishVideoIssue. On version 2.16.6 issue is not reproducable.

**Comment by jaoo** [comment] 2020-05-08 08:05
@NataliiaZarudna Thanks for filling this issue. We are working on it. Will comment here when we make progress on a fix.

**Comment by jaoo** [comment] 2020-05-08 15:11
On Android 5 our SDK uses (by default) a `android.hardware.Camera`-based video capturer. So you will get something like the following when creating the second publisher:

```
05-08 14:59:11.913 4333-4333/? D/[com.opentok.android.DefaultVideoCapturer]: init() enetered [com.opentok.android.DefaultVideoCapturer@38eb6c33] (1588942751913) {main}
05-08 14:59:11.913 1186-1751/? W/CameraService: CameraService::connect X (pid 4333) rejected (existing client).
05-08 14:59:11.913 4333-4333/? W/CameraBase: An error occurred while connecting to camera: 1
05-08 14:59:11.913 4333-4333/? E/[com.opentok.android.DefaultVideoCapturer]: The camera is in use by another app
    java.lang.RuntimeException: Fail to connect to camera service
        At android.hardware.Camera.<init>(Camera.java:497)

```

`onCameraError()` from https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Publisher.CameraListener.html is invoked.

In 2.16.X there was a cleanup process in place when disconnecting from the session. In 2.17.0 this cleanup process is performed somehow by the garbage collector (remember we have deprecated methods such as `Publisher.destroy()` and from 2.17.0 on, the garbage collector takes care of releasing resources such as the camera). 

Actually you do not need to create a new publisher for adding it once the session connects again. You can re use it.

You can test our `android.hardware.Camera2`-based video capturer by using `Session.SessionOptions` (https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionOptions.html) and enabling when creating the session. Note: android.hardware.Camera2 was added in API level 21.

**Comment by shakil807g** [comment] 2020-05-09 14:54
@jaoo @NataliiaZarudna  I am facing the same issue in 2.17.0, I have enable camera api 2 when creating the session using SessionOptions. Camera preview become black after publisher added to session second time.

**Comment by NataliiaZarudna** [comment] 2020-05-11 09:09
@shakil807g same issue for me.

@jaoo If I understand you correctly: if I use android.hardware.Camera2 then I can create new Publisher for each connection, or not? Or I need **always use same** Publisher to avoid issue with black video on Android 5?

**Comment by jaoo** [comment] 2020-05-11 09:34
Hello! I am sorry if I was not clear enough. You guys do not need to create a new publisher instance for the second time you connect to the session. The same publisher instance in the same activity is valid across different connect/disconnect cycles.

**Comment by NataliiaZarudna** [comment] 2020-05-11 09:40
The thing is that my activity is destroyed after a call (and in case when I create new activity and new publisher I'm facing issue above), so I need to keep this publisher object in some static field to use it for the next calls and next sessions. Won't there be any issue with resources that my static Publisher object will keep through all app living time?

**Comment by jaoo** [comment] 2020-05-11 10:04
Hello again. I am sorry but we do not understand how you are implementing your use case. If you have a new activity for each new session there would not be any problem with having a new publisher instance for each new session showing the view. The view from each new publisher should be shown with no issues.

**Comment by NataliiaZarudna** [comment] 2020-05-11 11:25
Hello! The case is like you said:
1. Start new activity for call
2. Connect to session
3. Create **new** Publisher object
4. Publish it to session
5. Disconnect from session
6. Finish call activity
7. Repeat steps 1-4

AR. Publisher's video is black.

Sample: https://github.com/NataliiaZarudna/OpenTokPublishVideoIssue.

**Comment by jaoo** [comment] 2020-05-11 13:06
Hello! I see now. Even with a different activity any new publisher cannot capture video because the first publisher has not released the camera.

We have an idea to avoid this but until it is implemented you should stop the publisher's video capturer once the session is disconnected. Please add the following at https://github.com/NataliiaZarudna/OpenTokPublishVideoIssue/blob/master/app/src/main/java/com/tokbox/android/tutorials/basic_video_chat/CallActivity.java#L85

```java
            mPublisher.getCapturer().stopCapture();
            mPublisher = null
```

```
W/CameraBase( 5308): An error occurred while connecting to camera: 1
E/[com.opentok.android.DefaultVideoCapturer]( 5308): The camera is in use by another app
E/[com.opentok.android.DefaultVideoCapturer]( 5308): java.lang.RuntimeException: Fail to connect to camera service
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at android.hardware.Camera.<init>(Camera.java:497)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at android.hardware.Camera.open(Camera.java:342)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at com.opentok.android.DefaultVideoCapturer.init(DefaultVideoCapturer.java:102)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at com.opentok.android.PublisherKit.lambda$onCaptureInitJNI$8$PublisherKit(PublisherKit.java:1078)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at com.opentok.android.-$$Lambda$PublisherKit$uhAQwu__7KOHJjWokP-NwEMH3_k.run(lambda)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at android.os.Handler.handleCallback(Handler.java:739)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at android.os.Looper.loop(Looper.java:135)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at java.lang.reflect.Method.invoke(Native Method)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/[com.opentok.android.DefaultVideoCapturer]( 5308): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/[com.opentok.android.DefaultVideoCapturer]( 5308):  [com.opentok.android.DefaultVideoCapturer@3eb3758] (1589198677781) {main}
D/[com.opentok.android.Publisher]( 5308): onCameraError() Camera device has failed: (null description) [com.opentok.android.Publisher@2aa443b] (1589198677783) {main}
```

**Comment by NataliiaZarudna** [comment] 2020-05-11 13:36
stopCapture makes the trick! Thanks a lot for your help!

**Comment by NataliiaZarudna** [comment] 2020-05-11 13:53
Sorry, but there is also an issue with audio. For the second call it becomes louder and badly recognizable, with some echo. We faced same problem with audio once previously when forgot to unpublish publisher in one of cases.

**Comment by jaoo** [comment] 2020-05-12 06:45
Let me have a look please. Thanks.

**Comment by jaoo** [comment] 2020-05-12 07:58
@NataliiaZarudna I cannot reproduce the audio issue. I would need some logs from you. Can you enable them and post them somewhere (maybe at https://gist.github.com) please? You can enable logging by adding `com.opentok.android.OpenTokConfig.setJNILogs(true);` at https://github.com/NataliiaZarudna/OpenTokPublishVideoIssue/blob/master/app/src/main/java/com/tokbox/android/tutorials/basic_video_chat/CallActivity.java#L186.

**Comment by NataliiaZarudna** [comment] 2020-05-12 11:24
Logs: https://gist.github.com/NataliiaZarudna/3ad543448aa927c3ca04924d2d07a29d (Pixel 2, Android 10).
Also it looks like it works ok on Android 5, but Android 10 has this issues.

**Comment by NataliiaZarudna** [comment] 2020-05-25 06:54
Hello! Do you have any updates or maybe you need some more logs from me?

**Comment by robjperez** [comment] 2020-05-28 14:04
Hi!

@NataliiaZarudna  Can you open a new issue with the problem? so we don't mix things here?

How are you reproducing the problem with the audio?

**Comment by rperezcubero** [comment] 2020-07-23 08:59
Going to close this since the original problem of the issue looks like it is solved.
Please reopen it if necessary

**Closed by rperezcubero** 2020-07-23 08:59 UTC
