### ISSUE TITLE
Size of SDK has doubled

### ISSUE THREAD

**Issue by danmajercak** [opentok/opentok-android-sdk-samples#474] opened 2023-08-09 08:14 UTC
**Describe the bug**
Since opentok-android-sdk 2.25.2, the size of sdk has doubled compared to previous version
Was that on purpose? What has changed tha size has grown so much?

**Screenshots**

![Screenshot 2023-08-09 at 10 06 04](https://github.com/opentok/opentok-android-sdk-samples/assets/88988681/77f7d08d-c37a-46d0-88a9-bb9aeed0ece9)
![Screenshot 2023-08-09 at 10 06 14](https://github.com/opentok/opentok-android-sdk-samples/assets/88988681/b93d7544-b561-423b-a209-084a561f6acc)

**Comment by v-kpheng** [comment] 2023-08-09 21:56
@danmajercak, the size of the SDK grew due to support for the Media Processor APIs, which was introduced as a beta feature in Android SDK 2.25.3.

**Comment by danmajercak** [comment] 2023-08-10 08:20
Does it have to be part of the original sdk? We currently do not want to use this beta feature. But increasing the size of sdk is a blocker for us. Couldn't it be created as a separate dependency and clients who would be interested in this feature would add it?

**Comment by emartynov** [comment] 2023-08-10 09:15
I saw that 2.25.2 also grew without the beta functionality announcement.

**Comment by goncalocostamendes** [comment] 2023-08-16 18:10
@danmajercak @emartynov as @v-kpheng mentioned, the SDK grew only due to Media Processor APIs, which provides Background Blur and video/audio custom transformers to publisher's media stream. Even though it was only introduced as a beta feature in Android SDK 2.25.3, it was already part of 2.25.2. 

We are working in a solution to provide Media Processor APIs as an additional dependency, but there is no ETA for it at the moment.

Meanwhile I ask to remain with v2.25.1 until further notice

**Comment by wlTrunks** [comment] 2023-09-21 08:58
is there any way to exclude this Media Processor API, size of sdk too big

**Comment by goncalocostamendes** [comment] 2023-09-21 11:40
@wlTrunks at the moment, there isn't. I would ask you to remain with v2.25.1. We are working on providing Media Processor functionalities as a plugin that you can add to the SDK, but we have not finalise it yet

**Comment by v-kpheng** [comment] 2023-10-03 16:22
Just wanted to share an update.  We'll work with product on this.  Hope we can deliver this in Q1.
I'll share a link to the internal ticket once it's created.

**Comment by ntustzeus** [comment] 2023-11-13 10:01
any solution or workaround to reduce the sdk size?
I build a project that import com.opentok.android:opentok-android-sdk:2.25.2

the apk size is larger than 100MB so I use "analyze apk" from android studio and it shows libopentok.so is about 40MB(in x86_64)

I enabled ProGuard but no help.

Can the sdk size be reduced?

![libopentok_so](https://github.com/opentok/opentok-android-sdk-samples/assets/6657439/4d75712a-d859-41a8-be1a-9d8761f45993)

**Comment by goncalocostamendes** [comment] 2023-11-13 10:38
@ntustzeus unfortunately there is no workaround to reduce the SDK size. I would ask you to remain with v2.25.1 if possible where the size is around half of v2.25.2. 

The size has increased on v2.25.2 because we introduced Media Processor functionalities such as Background Blur and Background Replacement. Since the size is an issue for multiple costumers, we are working on providing Media Processor functionalities as a plugin that can be added to the SDK or not.

We're tracking this internally: https://jira.vonage.com/browse/VPF-499. We expect to have it solved by Q1 2024.

**Comment by AlexMoumou** [comment] 2024-02-12 10:23
@goncalocostamendes Is there a workaround for the size right now in the latest versions? v2.25.1 is unusable because it has the issue with the disconnect events being late 20-30secs causing our users sessions to get messed up if they log out and log in to quickly?

**Comment by goncalocostamendes** [comment] 2024-02-13 11:30
@AlexMoumou the solution to this problem is on the final stage of development. It should be released in the following weeks

**Comment by omaiborodahj** [comment] 2024-04-29 11:45
@goncalocostamendes any updates on this issue?

**Comment by goncalocostamendes** [comment] 2024-04-30 16:49
@emartynov @ntustzeus @wlTrunks @AlexMoumou @omaiborodahj @danmajercak the decoupling was already implemented and merged into the main branch. In the next release 2.28.0, planned to be done by late May, a second lib OpenTok_Transformers will be opt-in. The OpenTok lib size returned to its normal size

**Comment by Panda-ref** [comment] 2024-05-30 10:46
@goncalocostamendes

Is there a known release date for 2.28.0? Is it still late May?

**Comment by ntustzeus** [comment] 2024-06-03 03:22
2024/6/3, it seems no new release note from offical site.

the issue is nothing about new feature but just to revert a clean version, how can it take 10 months and not completed?
Hope the new version will be well optimized before release.


![2024-06-03_110446-vonage-android-sdk](https://github.com/opentok/opentok-android-sdk-samples/assets/6657439/4b6580ca-0614-4a76-8101-48c30838b0d5)

**Comment by goncalocostamendes** [comment] 2024-06-03 18:22
@v-kpheng can you confirm 2.28.0 is comming up and if possible an ETA

**Comment by v-kpheng** [comment] 2024-06-03 18:52
@goncalocostamendes, ETA slipped to end of June.  Sorry.

**Comment by Panda-ref** [comment] 2024-07-04 11:28
@v-kpheng Any updates?

**Comment by goncalocostamendes** [comment] 2024-07-04 12:05
Android SDK 2.28.0 is already released and the opentok came back to its previous 



https://tokbox.com/developer/guides/vonage-media-processor/android/#:~:text=Vonage%20Media%20Library%20integration,code%200x0A000006%20%2D%20OTC_MEDIA_TRANSFORMER_OPENTOK_TRANSFORMERS_LIBRARY_NOT_LOADED.

**Closed** 2024-07-17 22:54 UTC
Labels: feature request
