### ISSUE TITLE
Black screen in video call when resume

### ISSUE THREAD

**Issue by gitanshubatra239** [opentok/opentok-android-sdk-samples#439] opened 2022-10-18 06:32 UTC
Getting a black screen when sending the app in background and resuming again. 
I've referred the same Camera file that has been provided in the repo

**Comment by v-kpheng** [comment] 2022-10-19 21:47
@gitanshubatra239, thanks for letting us know about the issue.

Some key details are left out, however, which makes root cause difficult.  I'm going to close this.  Can you please refile this issue and answer the questions in the template?  That'll help us out a lot, because it'll provide critical information.  Thanks!

**Closed by v-kpheng** 2022-10-19 21:47 UTC
