### ISSUE TITLE
Video is getting stretched when the number of stream is odd 

### ISSUE THREAD

**Issue by TooLazyy** [opentok/opentok-android-sdk-samples#171] opened 2018-05-22 15:41 UTC
Hi. I'm using com.opentok.android:opentok-android-sdk:2.12.0.
Copied some code from Multiparty-ConstraintLayout sample.
 1 - my preview playing full screen, right
 2 - when another stream received (2 pictures on the screen), my preview getting stretched, subscriber preview looks okay.
I thought it was my bad.... but not.

Multiparty-ConstraintLayout sample without any line changed has the same bug.
Same  [issue](https://github.com/opentok/opentok-android-sdk-samples/issues/160) has been closed without any fix.
Screens has provided.

![default](https://user-images.githubusercontent.com/18148514/40373457-9de55ff4-5def-11e8-930d-d42fee227438.png)
![2018-05-22 18 34 37](https://user-images.githubusercontent.com/18148514/40373334-59821eba-5def-11e8-9cbe-68361db55c6b.jpg)

**Comment by marinaserranomontes** [comment] 2018-07-17 16:16
Hi @TooLazyy,

We were able to reproduce it. We are going to take a deep look to that. 

Thanks to report it.

Best,
Marina

**Comment by marinaserranomontes** [comment] 2018-07-23 13:55
I’m closing this issue because it is not reproducible in the latest SDK version.

Please reopen if you still encounter this issue You can also contribute directly by providing a patch.

Thank you!

**Closed by marinaserranomontes** 2018-07-23 13:55 UTC

**Comment by Abhisheksnapwiz** [comment] 2019-07-30 06:49
I am getting similar issue in IOS app. I have one stream which is showing in full screen and another stream is showing in small screen when I tried to toggle in between then video is getting stretched. I am following similar way to provide frame as it in demo app for Multiparty IOS app. Please assist  How can we fix this issue.

**Comment by rituapplocum** [comment] 2022-05-27 10:26
I m displaying Subscriber name on TextureView and it is getting stretched
